Move the caching support over to an API
SimpleMachines/SMF pull request #3703
Opened 2016-12-05 02:55 UTC by jdarwood007

This implants a Class-CacheAPI that defines our supported setup.  Our supported cache methods have been converted over.

This conflicts with #3697
This resolves #3693 

Please test this well.  I've tested with SMF, APCu and Memcache.

Signed-off-by: jdarwood007 <unmonitored+github@sleepycode.com>

2016-12-05 18:04 UTC, MissAllSunday commented
For some reason my server isn't using the memcached class, it correctly detects memcached but it continues to use smf file based cache

I believe its because of this:

```php
	$tryAccelerator = !empty($overrideCache) ? $overrideCache : !empty($cache_accelerator) ? $cache_accelerator : 'smf';
``

!empty($cache_accelerator) will always gonna return false since that var ($cache_accelerator) isn't defined prior to that check so $tryAccelerator will always be assigned to "smf";

2016-12-05 18:18 UTC, MissAllSunday commented
$cache_accelerator wasn't globalized.

After added to the global scope I now get this error:

PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /Sources/CacheAPI-memcached.php:103

2016-12-06 00:02 UTC, jdarwood007 commented
Oh my, your right.  My testing yesterday was falling back to SMF file caching.  Try the most recent changes, I forgot to call the connect.

2016-12-06 05:32 UTC, albertlast commented
The whole class thing i personaly only know from java topics and
one thing which looks to me "wrong" that you got set and get function for like defaultttls (this is good) and
on the other side public vars ttl.

Is that a good idea to keep them public instead of make them private or protected? (maybe that doesn't work in php i dont know...)

2016-12-06 23:50 UTC, jdarwood007 commented
Well if we didn't want them public, we would have to make them protected, since the base class gets extended and contains those members.

Does it offer us any advantage here?  There isn't any sensitive stuff being passed around really.  The only stuff I could think off is the memcache instances and its private from the class it extends.

2016-12-06 23:52 UTC, MissAllSunday commented
Got a new error:

Fatal error:  Uncaught Error: Call to a member function getServerList() on null in /Sources/CacheAPI-memcached.php:60

It seems $this->memcached is never created as an instance of Memcached class

2016-12-06 23:56 UTC, jdarwood007 commented
Are you sure its memcached and not memcache?

https://secure.php.net/manual/en/memcached.getserverlist.php

That should exist

2016-12-06 23:59 UTC, MissAllSunday commented
Thats not the issue, the issue is that  $this->memcached is always null,  it doesn't hold an instance of Memcached.  There should be a new instance somewhere in the memcached class:

$this->memcached = new Memcached;

2016-12-07 00:04 UTC, jdarwood007 commented
I used $this->memcache for memcached as well. I can change that, its just a naming convention at that point

2016-12-07 00:04 UTC, jdarwood007 commented
Oh wait, I see now.  Getting confused with memcache and memcached

2016-12-07 00:07 UTC, MissAllSunday commented
nope....

public function connect()  uses the property $this->memcached  which is defined as null.  It never holds an instance of Memcached  so it remains as null.

When connect() gets called and $currentServers is defined, $this->memcached is still null.

Before $this->memcached is used, it must contain an instance of Memcached:

$this->memcached = new Memcached;
 $currentServers = $this->memcached->getServerList();

2016-12-07 00:13 UTC, jdarwood007 commented
Yep.  Fixed it hopefully?

2016-12-07 00:24 UTC, MissAllSunday commented
yep but now I got a new one:

Memcached::set() expects at most 3 parameters, 4 given	/Sources/CacheAPI-memcached.php
Line: 125

the set() method in memcached is slightly different than that one memcache uses.

2016-12-07 00:30 UTC, jdarwood007 commented
Oh so it is, it doesn't offer compression methods in the set.

2016-12-07 00:37 UTC, MissAllSunday commented
All working now, will leave it for a couple of days to see if theres any more issues

2016-12-07 00:39 UTC, MissAllSunday commented
oops, nvm, a nre error:

Json decode error: Syntax error, malformed JSON	h
File: /Sources/Load.php
Line: 3379

return empty($value) ? null : smf_json_decode($value, true);

The json data is the one coming from memcached, will take a look at it.

2016-12-07 00:48 UTC, jdarwood007 commented
Is $value returning as something else?

I detect if $value was exactly false (=== test) and return null, otherwise return the value.  This is supposed to catch anything that may be considered empty such as 0 but still a stored value.

2016-12-07 01:14 UTC, MissAllSunday commented
yeah thats what I've been trying to do, it seems the error is generated every time this url gets called:

https://missallsunday.com/index.php?favicon=ico

I don't know if that param (favicon) is included on a vanilla SMF installation or its a part of some of the mods I have installed. It fails and gets redirected back to my index.

 Can't find any code that handles that particular url so I can't detect what exactly its been retrieved from the cache.

2016-12-07 01:16 UTC, jdarwood007 commented
That looks like a mod.  I don't recall any such thing, nor does it work on my test site. https://dev.sleepycode.com/smf21git/index.php?favicon=ico

2016-12-07 01:23 UTC, MissAllSunday commented
I think my browser its generating that url and simpleSEF if redirecting it. Thats the only mod I have that could be causing it.

2016-12-07 01:38 UTC, MissAllSunday commented
Just disable simpleSEF and the error is gone so yeah, its related to it, will have a look and fix it within the mod: https://github.com/MissAllSunday/SimpleSEF/issues/6

2016-12-07 05:37 UTC, albertlast commented
> Does it offer us any advantage here? There isn't any sensitive stuff being passed around really. The only stuff I could think off is the memcache instances and its private from the class it extends.

sure is there advantage, when you got only set and get function public, your are able to place check logic if the value is correct for this var for exp $keyprefix var is a Ä or ü or ` valid chars?
other advantage is your can place update logic "when the ttl is changed than i had to update the whole cache" with public vars you got no chance todo so.

one additional note i would like to see that prefix function and the prefix key got the same name
$keyPrefix vs setPrefix

2016-12-08 03:13 UTC, jdarwood007 commented
Well I suspect that UTF-8 would be supported in keys for all the caching APIs, since they support storing UTF-8 data.

I fixed up those changes.  I prefer set/get/pud/etc at the start of most methods because it defines a clear accepted action (updating/changing data or retrieving)

2016-12-10 09:03 UTC, live627 requested changes
- the @inheritdoc blocks can and should be on all of the extending classes
- you forgot to include a clear() met5hod... https://github.com/SimpleMachines/SMF2.1/blob/aafc00003fae1129ed2e0567e3e5402b8e484787/Sources/Subs.php#L3950
- i hate jqwarry

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-apc.php
> +	public function connect()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-apc.php
> +	public function quit()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-apcu.php
> +	public function connect()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-apcu.php
> +	public function quit()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-smf.php
> +	public function connect()
these functions that don't do anything should be moved to the base class, less duplication

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-smf.php
> +//		$this->setPrefix('');
Debugging leftover...

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-smf.php
> +	public function quit()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-xcache.php
> +	public function connect()
Needs authentication here to be able to clear all, related to #3644

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-xcache.php
> +	public function quit()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-zend.php
> +	public function connect()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-zend.php
> +	public function quit()
these functions that don't do anything should be moved to the base class, less duplication.

2016-12-10 09:03 UTC, live627 commented on Sources/Class-CacheAPI.php
> +	public function getData($key, $ttl = null)
These empty stubs should be removed since they all should already have been implemented in the extending objects.

2016-12-10 09:03 UTC, live627 commented on Sources/CacheAPI-smf.php
> +			@include($cachedir . '/data_' . $key . '.php');
Could we move to JSON here? IMO it would be better than abusing PHP files for this...

2016-12-13 20:47 UTC, jdarwood007 commented on Sources/Class-CacheAPI.php
> +	public function getData($key, $ttl = null)
Fixing this causing abstract errors on the individual APIs themselves.  Marking the individual APIs abstract causes more errors.  Not sure if we want to do it this way.

2016-12-13 20:48 UTC, jdarwood007 commented on Sources/CacheAPI-xcache.php
> +	public function connect()
PHP 7 doesn't appear to have xCache so I can't test this, but implanting the code that may possibly work.

2016-12-13 20:57 UTC, jdarwood007 commented
I left the JSON issue out of this for now.  We should discuss if we want to move the SMF file caching over to JSON separately.  File Based caching is fairly stable compared to when it was first released.  I don't know if we want to cross that hurdle again by moving to JSON right now.

2016-12-13 20:58 UTC, jdarwood007 commented
As well, I moved the clear function to Load.php with the other cache stuff.  Makes more sense I think to have all the caching code together in Load.php rather than in Subs.php as well.  We can revert this change if needed.

2016-12-14 05:30 UTC, albertlast commented on Themes/default/languages/ManageSettings.english.php
> +$txt['cache_xcache'] = 'XCache settings';
cache_xcache vs xcache_cache it's from my pov to near,
i would like to see somthing like that cache_xcache -> xcache_setting
to keep inline with the other fields and let to be clear.

2016-12-14 22:47 UTC, jdarwood007 commented
Hows that.  I think that makes it more clear.

2016-12-25 23:55 UTC, merged