Lint all the things
SimpleMachines/SMF pull request #3719
Opened 2016-12-11 00:34 UTC by live627

Someone should enable builds on Travis CI

2016-12-12 05:42 UTC, colinschoen requested changes
Not sure what Subs is being changed for.

2016-12-12 05:42 UTC, colinschoen commented on Sources/Subs.php
> -					$new_key .= explode('(?'.'>', $sub_regex)[0];
What is this change for?

2016-12-12 06:14 UTC, live627 commented on Sources/Subs.php
> -					$new_key .= explode('(?'.'>', $sub_regex)[0];
PHP 5.3 compatibility.

2016-12-18 19:21 UTC, colinschoen commented
@CoreISP or @Oldiesmann (or whoever has owners access) can we enable the travis CI extension.

2016-12-21 07:50 UTC, colinschoen approved these changes

2016-12-22 22:31 UTC, colinschoen commented
Bump

2016-12-24 04:19 UTC, merged

2016-12-27 02:57 UTC, jdarwood007 commented
@colinschoen,

I am asking @Oldiesmann to setup travis.  Although at this point I'm not sure what use it would be without some proper tools to test with.  Do you have stuff in mind?  We do have a unreleased PHP unit that was for testing BBC and a few other things sitting around.  I think if you are willing to take on that PHP unit, we could get it updated, released and pushed for Travis CI to use.

2016-12-27 03:19 UTC, colinschoen commented
Thanks, yes willing to take that on.

2016-12-27 03:20 UTC, jdarwood007 commented
https://travis-ci.org/SimpleMachines/SMF2.1

@Oldiesmann has set it up btw.