added return value to db_insert
SimpleMachines/SMF pull request #3736
Opened 2016-12-22 09:16 UTC by albertlast

I saw many places where after db_insert the db_insert_id is calling
and i realize that the db_insert function is able to insert multipe values at once but then the db_insert_id get then broken.

So with this pr I solve this issues your are able to get directly the id back and
when your insert multiple values your get multiple id's.

To handle this different needs I place different returnmods = 
0 do nothing (default)
1 return the id of the last row
2 return an array of all id of every row

The challange is here that mysql is less potential as pg.
in pg last insert id works on all insert mode, on all type of fields and unlimited number of fields in the table
in mysql last insert works only on normal insert (no replace or ignore), only on ai fields and only one field

The first limitation of mysql I implemented in pg that the return only works on method == ''
for the second I don't see any checks
the last one when multiple keys are provided I take the first one -> the first one needs to be the ai field.

When this pr is merged,
the next step would be to remove the places where db_insert_id is used.

2016-12-22 22:35 UTC, colinschoen commented on Sources/Subs-Db-postgresql.php
> +			if($with_returning && $request !== false && $row = $smcFunc['db_fetch_assoc']($request, count($insertRows) - 1))
`if (` instead of `if(`

2016-12-22 22:35 UTC, colinschoen commented on Sources/Subs-Db-mysqli.php
> +		if ($returnmode == 1)
Switch here too

2016-12-22 22:35 UTC, colinschoen commented on Sources/Subs-Db-mysql.php
> +		if ($returnmode == 1)
Can we use a switch here.

2016-12-22 22:35 UTC, colinschoen commented on Sources/Subs-Db-postgresql.php
> +				if ($returnmode == 1)
Switch

2016-12-22 22:35 UTC, colinschoen commented on Sources/Subs-Db-postgresql.php
> +	if($with_returning && !empty($return_var))
`if (` instead of `if(`

2016-12-22 22:35 UTC, colinschoen requested changes
Nits

2016-12-23 05:26 UTC, albertlast commented on Sources/Subs-Db-mysql.php
> +		if ($returnmode == 1)
With switch your mean case?
Why should be a case here better as if?
use more space/loc and we got only two possibilities

2016-12-24 04:40 UTC, live627 commented on Sources/Subs-Db-mysql.php
> +		if ($returnmode == 1)
why use a switch if only two permutations?

2016-12-24 04:42 UTC, live627 requested changes

2016-12-24 04:42 UTC, live627 commented on Sources/Subs-Db-mysql.php
> + * @param returnmode 0 = nothing(default), 1 = last row id, 2 = all rows id as array; every mode runs only with method = ''
invalid docblock, should be `@param int $returnmode`

2016-12-24 04:55 UTC, colinschoen commented on Sources/Subs-Db-mysql.php
> +		if ($returnmode == 1)
Agreed, not needed. Apologies, disregard this comment.

2016-12-24 04:56 UTC, colinschoen commented on Sources/Subs-Db-mysqli.php
> +		if ($returnmode == 1)
Disregard

2016-12-24 04:56 UTC, colinschoen commented on Sources/Subs-Db-postgresql.php
> +				if ($returnmode == 1)
Disregard

2016-12-24 06:29 UTC, albertlast commented on Sources/Subs-Db-mysql.php
> + * @param returnmode 0 = nothing(default), 1 = last row id, 2 = all rows id as array; every mode runs only with method = ''
Int would be not fully true,
from technical pov is int[] when returnmode is 2 and
when you use pg string and string[] is possible, too.

That was I mean with:

> only on ai fields -- for the second I don't see any checks

i mean we could hide this behavior if we that don't mention ...

2016-12-24 08:50 UTC, albertlast commented on Sources/Subs-Db-postgresql.php
> +				if (is_int($row[$keys[0]])) // try to emulate mysql limitation
I'm not 100% sure if I should do this,
but this in my eyes the only way to check if the fields is a ai field(int).

The main fokus is for person how develop something on smf with pg and
hop the stuff is running on mysql too.
But on the other side maybe is this behavior for this mod/addon (not only we develop for smf)
not important...

2016-12-24 08:54 UTC, albertlast commented on Sources/Subs-Db-postgresql.php
> +				if (is_int($row[$keys[0]])) // try to emulate mysql limitation
I'm not 100% sure if I should do this,
but this in my eyes the only way to check if the fields is a ai field(int).

The main fokus is for person how develop something on smf with pg and
hop the stuff is running on mysql too.
But on the other side maybe is this behavior for this mod/addon (not only we develop for smf)
not important...

2016-12-24 08:58 UTC, albertlast commented
So I clean up and reduce the dupplicate of logic.
And place a check if the return value is a integer.

But like I already mansion,
i'm not sure how fare i should emulate the limitation of mysql in pg.

implementet behavior
- only mode ''
- only the first key
- only int

2016-12-29 08:33 UTC, albertlast commented
@live627 oldiesmann mention that we doesn't want api change in rc1.
so u are sure about for targeting this for rc1?

2016-12-29 09:17 UTC, live627 commented
changed it back

2017-01-02 03:05 UTC, merged