Align transaction handling
SimpleMachines/SMF pull request #3777
Opened 2017-01-02 17:16 UTC by albertlast

Drop the transaction handling in pg because mysql doesn't support this.
And i'm lazy -> i build this pr on the rewrite db_insert_id pr
to see only the real changes: https://github.com/albertlast/SMF2.1/commit/df30aa0f3a5118f0f256569e03e2e1697837be65

2017-01-02 17:23 UTC, jdarwood007 commented
MySQL supports transactions http://dev.mysql.com/doc/refman/5.7/en/commit.html

I'm having trouble finding when it was added, but far as I can tell it has existed since 3.23.28 and is only supported on InnoDB tables (no MyISAM).

2017-01-02 17:25 UTC, albertlast commented
i know that it's support transaction,
but i don't like that db_insert works differently between mysql and pg.
the other way would be to add this to mysql too.

2017-01-02 17:26 UTC, jdarwood007 commented
Ok, I see your commit now.  Removing it from the insert function is fine, if we need to call the transaction we can do it ourselves rather than in the insert function.

2017-01-04 04:08 UTC, live627 requested changes

2017-01-04 04:08 UTC, live627 commented on Sources/RepairBoards.php
> +						array('id_topic'),
This should be `id_msg`

2017-01-04 04:08 UTC, live627 commented on Sources/RepairBoards.php
> +					array('id_topic'),
Same as above.

2017-01-05 06:41 UTC, merged