Add input "URL"
SimpleMachines/SMF pull request #3822
Opened 2017-01-09 17:27 UTC by jsDotx3

Add input url for "og_image" setting

Signed-off-by: José <jsdotx3@gmail.com>

2017-01-10 00:52 UTC, live627 requested changes

2017-01-10 00:52 UTC, live627 commented on Themes/default/Themes.template.php
> +			<input type="url"';
Please keep the indenting uniform with the rest off the file.

2017-01-10 00:56 UTC, jsDotx3 commented on Themes/default/Themes.template.php
> +			<input type="url"';
Ready, is good?

2017-01-10 00:57 UTC, Antes commented
You have to sign-off each commit not just first one.

2017-01-11 11:33 UTC, merged

2017-01-11 11:34 UTC, live627 commented
Squashed to single commit with the sign.