Fix upgrade migration of fields from members to themes
SimpleMachines/SMF pull request #3842
Opened 2017-01-15 06:09 UTC by sbulen

To address: Upgrade Issue - Can't get past Step 4 #3833

2017-01-15 06:41 UTC, albertlast requested changes

2017-01-15 06:41 UTC, albertlast commented on other/upgrade_2-1_mysql.sql
> +				array('id_member', 'id_theme', 'variable', 'value')
value field can't be a pk field.
and the pk is defined as 'id_theme', 'id_member', 'variable' -> i would keep the old arrengment

2017-01-15 06:41 UTC, albertlast commented on other/upgrade_2-1_mysql.sql
> +				$inserts[] = array($row['id_member'], 0, 'cust_aolins', $row['aim']);
-1 looks as the right default value (the datebase can handle -1)
the same for the other changes.

2017-01-15 06:42 UTC, albertlast commented
Please consider that all mysql changes needs to be sync with pg upgrade when ther are right,
what in my eyes here not the true is.

2017-01-15 07:01 UTC, albertlast commented on other/upgrade_2-1_mysql.sql
> +				$inserts[] = array($row['id_member'], 0, 'cust_aolins', $row['aim']);
i looked on the wrong col,
the -1 is in theme_id col...
here are -1 value not allowed -> 0 or even 1 could be right

2017-01-15 07:20 UTC, sbulen commented on other/upgrade_2-1_mysql.sql
> +				array('id_member', 'id_theme', 'variable', 'value')
OK.  Will revise & test.

2017-01-15 07:51 UTC, sbulen commented
Added the pg updates.  I don't have pg, so I can't test them, but they're simple enough. 

I left the pk line alone.  That makes sense.  Thanks for the insight.  

FYI - I have tested with a theme_id of 0 as well as a theme_id of 1 here.  The theme_id of 0 I believe corresponds to the default, and is a little more consistent with what I read elsewhere in this code.  

When you use 0, the profiles of forum members are visible with this info throughout the forum, which I think is desired.

2017-01-15 08:09 UTC, albertlast commented
Someone else had to say if theme_id 0 is a valid value for this context,
i only mention the database side.

2017-01-18 05:12 UTC, live627 commented on other/upgrade_2-1_mysql.sql
> +				$inserts[] = array($row['id_member'], 0, 'cust_aolins', $row['aim']);
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L1753

Probably should be `1`

2017-01-18 07:03 UTC, sbulen commented on other/upgrade_2-1_mysql.sql
> +				$inserts[] = array($row['id_member'], 0, 'cust_aolins', $row['aim']);
I think you're right...   Let me fix this...
I just added a bunch of these attributes manually online, & they all get added with a theme_id of 1.
I think the data migration should mimic the manual data entry, so I'll set it to 1.

2017-01-18 07:14 UTC, sbulen commented
Changed to theme_id of 1, per discussion above.  Thanks for the input!

2017-01-19 06:13 UTC, merged