Issue setlocale to enable utf8 processing in certain php functions
SimpleMachines/SMF pull request #3948
Opened 2017-02-23 04:55 UTC by sbulen

php functions such as basename() and pathinfo() require setlocale to be set in order to properly operate with the utf8 character set.  

basename() and pathinfo() are safe & preferred methods operate on uploaded files, and provide protection from file traversal attacks.  Both are used throughout SMF today.  This PR makes them utf8-friendly.

This PR negates the need to write our own version of pathinfo or basename, & replaces PR #3887 

Feedback welcome,

2017-02-23 06:01 UTC, albertlast commented
I think it's the right way,
only i ask my self if maybe important to change language.
In your pr is this hardcoded "en_US" i mean this is better as nothing,
but maybe we should be able to change this value by settings/vars?

2017-02-23 06:35 UTC, sbulen commented
@albertlast - Great question.  Note that we focused on LC_CTYPE - which focuses on character processing.  

_If we needed to specify another locale category, e.g., LC_MONETARY or LC_TIME, we would absolutely have had to offer an SMF setting to control it._  

I did a number of searches on this issue, and they all used that exact string to resolve it.  Given that it supports all UTF8 characters, I'm not sure another language setting would make a difference?  

Note that these locale strings are OS dependent as well.  setlocale() will try anything you feed it and ignore errors - it understands you may be feeding it a few things to try to attempt to provide multi-OS support.  The errors we observed were Linux specific, and this is the Linux string to remedy the problem.

2017-02-23 21:34 UTC, Antes commented
@sbulen why are you setting this as en_US.utf8 ? You should call $txt['lang_locale'] which returns locale in the language active.

2017-02-23 21:49 UTC, sbulen commented
I wasn't aware of $txt['lang_locale']...  Hadn't run across it yet!  

How is it updated/maintained?  Is it safe to use in setLocale()?   If so, I'll make that change.   It'll take me a few days, I'm now travelling again & don't have access to my dev environment.  

I see this entry in index.english.php as well:
    $txt['lang_character_set'] = 'ISO-8859-1';

Is this correct, or should it reflect UTF8?  

If so, I'll do that as well.

2017-02-27 06:52 UTC, sbulen commented
Updated per request

2017-02-27 15:00 UTC, XinYenFon requested changes

2017-02-27 15:00 UTC, Antes commented on Themes/default/languages/index.english.php
> +$txt['lang_character_set'] = 'UTF-8';
Please keep this as is, our language editor already taking care of this part based on the output :)

2017-02-27 18:21 UTC, sbulen commented
@Antes - OK...  But just to be sure...  

I think this setting is overwriting UTF-8 processing in multiple places throughout the app.  For example, in Load:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L75
Also:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L2077

A grep reveals there are numerous other places this is used, and negating UTF-8 processing.   

If $txt['lang_character_set'] is intended to be used by the language editor, then maybe these other instances should be changed to use $modSettings['global_character_set']?

2017-02-27 21:41 UTC, Antes commented
That probably requires code cleanup because SMF 2.1 didn't started with utf8 only.

2017-02-28 01:31 UTC, sbulen commented
How's this?

2017-02-28 10:37 UTC, XinYenFon approved these changes

2017-03-02 23:37 UTC, Antes commented
whelp my stupidity forgot to say, can you please revert (remove) comment line in language file. If you drop by IRC some time, i can explain how our LE works and how your comment changes description of string :/

2017-03-02 23:52 UTC, sbulen commented
Done.   

I thought the comment would be helpful - folks such as myself would think it was missed.

2017-03-03 20:02 UTC, sbulen commented
@Antes - I'll take you up on that offer!   I haven't used IRC in about 20 years, though...   Let me know what server/room you're on & I'll find a way there.

2017-03-03 20:20 UTC, Antes commented
@sbulen http://www.simplemachines.org/community/index.php?topic=183880.0

2017-03-11 19:40 UTC, merged