Optimize the amount of queries for calendar
SimpleMachines/SMF pull request #3981
Opened 2017-03-21 10:10 UTC by albertlast

It could be happen that the same member got many event,
the query how get the timezone from the member is called once per event.

this code "cache" the result for every member.

2017-03-21 23:21 UTC, Sesquipedalian approved these changes

2017-03-21 23:28 UTC, colinschoen requested changes
Nit

2017-03-21 23:28 UTC, colinschoen commented on Sources/Subs-Calendar.php
> +	if(isset($id_member) && isset($member_cache[$id_member]))
`if (`

2017-03-23 04:29 UTC, colinschoen commented
Any reason we aren't using `cache_put_data` and `cache_get_data`?

2017-03-23 04:41 UTC, albertlast commented
Sure,
wouldn't solve the issue instead of ~2k time we query the databse,
we then 2k times access the cache -> the runtime keep the same.

With the static call we redurce the amounts of calls.

2017-03-23 05:44 UTC, Sesquipedalian commented
Yeah, a static variable is the better solution here for sure.

2017-03-23 05:47 UTC, colinschoen approved these changes
Makes sense. This looks like a good improvement. LGTM, approval

2017-03-23 05:47 UTC, merged