FixDoubleQuotes in PG fix #4005
SimpleMachines/SMF pull request #4007
Opened 2017-04-09 05:34 UTC by albertlast

Fix #4005

2017-04-10 02:57 UTC, jdarwood007 commented on Sources/DbSearch-postgresql.php
> +	$db_values = str_replace('"',"'",$db_values);
db_values is an array?

2017-04-10 03:46 UTC, albertlast commented on Sources/DbSearch-postgresql.php
> +	$db_values = str_replace('"',"'",$db_values);
sure but str_replace can handle array and return array.

2017-04-10 21:44 UTC, jdarwood007 commented on Sources/DbSearch-postgresql.php
> +	$db_values = str_replace('"',"'",$db_values);
Ahh, so it does.  Never noticed that.  Carry on.

2017-04-17 04:40 UTC, colinschoen requested changes
nits

2017-04-17 04:40 UTC, colinschoen commented on Sources/DbSearch-postgresql.php
> +	$db_values = str_replace('"',"'",$db_values);
Super nit: 

`$db_values = str_replace('"', "'", $db_values);`

2017-04-17 05:24 UTC, colinschoen approved these changes
LGTM, approval

2017-04-17 05:24 UTC, merged