added insert as method for return
SimpleMachines/SMF pull request #4087
Opened 2017-06-03 10:54 UTC by albertlast

for me was methode  '' = insert
forgot that methode 'insert' exists too.

2017-06-05 22:10 UTC, Sesquipedalian requested changes

2017-06-05 22:10 UTC, Sesquipedalian commented on Sources/Subs-Db-mysql.php
> +	if(!empty($keys) && (count($keys) > 0) && ($method === '' || $method === 'insert') && $returnmode > 0)
In this case, it would be more efficient to test if `$queryTitle === 'INSERT'` rather than if `($method === '' || $method === 'insert')`

2017-06-06 05:03 UTC, albertlast commented
Well i like to be that the check is the same on mysql and pg side.
pg doesn't hav this line of code.

2017-06-06 05:14 UTC, Sesquipedalian commented
I see your point, yes. My suggestion would only make the difference of a few microseconds, after all.

2017-06-06 05:14 UTC, Sesquipedalian approved these changes

2017-06-06 05:16 UTC, Sesquipedalian commented
There's a conflict that needs to be resolved before merging.

2017-06-06 15:28 UTC, Sesquipedalian commented
Hey @colinschoen or @live627, do you know why Travis is complaining about an unsigned commit in bdbd6c3? It's just a merge commit, so it shouldn't need to be signed.

2017-06-06 20:22 UTC, Oldiesmann commented
@jdarwood007 Any ideas on why travis is failing on the merge commit?

2017-06-06 22:26 UTC, colinschoen commented
Does travis even differentiate between merge commits and other commits? They look the same.

2017-06-06 23:14 UTC, jdarwood007 commented
Because Travis is looking at the pr merge and the merge itself for comments mentioning the sign off by.  It can fail as it only looks so far back in the history.  Its more difficult for me to program the automatic detection of the sign off than it is for us to check.

I'm thinking we could tie in https://www.clahub.com/ as a way to ensure they have signed the DCO, which I think reduces as much worry about signing off commits.  The CLA would cover the DCO and our generic CLA.

2017-06-08 04:16 UTC, merged