Benchmark for smf
SimpleMachines/SMF pull request #4088
Opened 2017-06-03 13:14 UTC by albertlast

Something I like to wish since start of my dev,
a way the benchmark smf.

for different motivation:
- changes on database stuff (dev stuff)
- changes on hardware
- changes on software releases (change of php or database version)

the second and last point i believe it's a common issue and not special like the first one.

2017-06-03 14:57 UTC, jdarwood007 commented
Should note that registerMember is a really really slow function.  I believe during my testing it came down to the password creation as hash_password was designed to be slow.

2017-06-03 19:57 UTC, albertlast commented
Well this in my eyes no problem.

I did some test in my env.

mysql
-user 81
-topic 72

postgres
-user 112
-topic 7789

Dunno why the numbers with pg so mutch higher than mysql (i believe my mysql is not so good).
But it's shows that the user creation is mutch more cpu/php heavy task is and
the topic run more database releated is.

And this in my eyes a good mix.

2017-06-04 09:22 UTC, albertlast commented
Added a third methode,
this try to access a topic x times in one minutes.

This benchmark shows realy good how many topic a user can access,
because this stuff depend on many things like size of the board and activate features.
It's show realy good the status of the board,
but this make it's hard for comparing accross with different board.

Because it's show how a mod, feature or size effect the board,
make this test veary valuable for board admins.

2017-06-04 19:10 UTC, colinschoen requested changes
This benchmarking has some side effects of affecting statistics and increasing unique IDs substantially if run often.

2017-06-04 19:10 UTC, colinschoen commented on Sources/ManageMaintenance.php
> + * Benchmakr for User creation tries to create as many as possible in 1 minute
`Benchmakr` -> `benchmark`

2017-06-04 19:10 UTC, colinschoen commented on Sources/ManageMaintenance.php
> + * Benchmakr for Post reads tries to access as many as possible in 1 minute
`Benchmakr` -> `Benchmark`

2017-06-04 19:10 UTC, colinschoen commented on Themes/default/languages/ManageMaintenance.english.php
> +$txt['benchmark_post_info'] = 'Create as many posts as possible in one minute <br/> This test is db insert imperformance heavy';
`imperformance` -> `performance`

2017-06-04 19:10 UTC, colinschoen commented on Themes/default/languages/ManageMaintenance.english.php
> +$txt['benchmark_topic'] = 'Benchmark methodes';
`Benchmark methodes` -> `Benchmark methods`

2017-06-04 19:10 UTC, colinschoen commented on Themes/default/languages/ManageMaintenance.english.php
> +$txt['benchmark_postread_info'] = 'Access a topic how often it can in one minute <br/> This test dipence heavy on the size of your board and active features';
`Repeatedly access a topic for 1 minute. <br /> This test depends heavily on the size of your board and the active features.`

2017-06-04 19:15 UTC, albertlast commented
The statistics are not touched as fare i see in my test env.
I see no problem with raising the unique id's in db tables,
max int is 2147483647 in my test was max 8k for topic creating stuff...

2017-06-04 20:04 UTC, jdarwood007 commented
Would this only have use for development/testing?

I'm not seeing this as something that is meant for a production site.  Perhaps it would be best split off into a separate utility that we could expand and maintain as part of benchmark and/or unit testing

2017-06-04 21:10 UTC, albertlast commented
i already sayed my point of in the first commit,
in short i see need on admin side too.

2017-06-04 21:37 UTC, Antes commented
I disagree this is a bloated addition to core.

2017-06-05 21:50 UTC, Sesquipedalian commented
This kind of benchmarking is definitely useful, @albertlast. But I agree with the others that it would be better to develop it as a separate mod or utility. That would give you more flexibility to adjust the various types of benchmarks and add new ones over time. By the look of things, you should be able to do everything via integration hooks.

2017-06-06 04:35 UTC, albertlast commented
I take from the last comments basicly: "The dev do the thing" 
Can someone show me the person
how test smf with all variation of php version are supported,
all databases types and version,
different sizes of boards,
with the different combination of mods and
hardware/webspace configuration which is smf running?

When you can not mention this guy than is my eye not provided by the dev "guy" and
the smf admin had to do this stuff.

2017-06-06 05:02 UTC, Sesquipedalian commented
What we are saying is that if you make it a mod for this, then anyone who feels the need to do some benchmarking can just install the mod and do as much as they like. It should be pretty easy to make a mod out of this, and in fact you should be able to do it entirely using integration hooks.

2017-06-06 05:04 UTC, albertlast commented
But i will create no mod,
this type of information are essential,
when this type is not essential we should drop function like calendar too.

2017-06-06 05:05 UTC, Antes commented
What? How you correlate calendar with benchmark ?

2017-06-06 05:07 UTC, colinschoen commented
The issue is that 99% of forum owners won't use the utility. It is however extremely useful for the 1%, but that means it is likely better as a mod to install for those that will use it.

2017-06-06 05:14 UTC, Antes commented
On the other hand, you can tweak https://github.com/SimpleMachines/tools/blob/master/Populate.php to do benchmark as well as the populate or create whole new file like populate (benchmark.php) to make it happen.

2017-06-06 13:44 UTC, albertlast commented
Populate is the wrong tool to benchmark your smf,
please don't use it for this case...

2017-06-06 20:05 UTC, Sesquipedalian commented
Using the `integrate_admin_areas` and `integrate_manage_maintenance` hooks, you should be able to make a mod for this that does everything you want, @albertlast. The consensus seems to be that this would be the best approach to follow.

2017-06-06 20:05 UTC, closed without merging

2017-06-06 20:17 UTC, albertlast commented
When you mean this benchmark would be good for dev,
why you not keeping this and activate only when $db_show_debug=true; is on.

From my side will be no mod.

2017-06-06 20:18 UTC, colinschoen commented
The issue isn't that it is hidden or visible, but that it inflates the code base which we have to maintain for a feature that will likely be used by ~1% of the users. What is your hesitate to convert this into a mod?

2017-06-06 20:21 UTC, albertlast commented
Why you not create a mod the code is there?
Easy anwser the issue the support.

2017-06-06 20:22 UTC, colinschoen commented
^ Sorry, I don't understand. Can you rephrase.

2017-06-06 20:23 UTC, albertlast commented
provide a mod create man support task and i'm not willig to do so,
when you mean that is important than feel free to take the code an create mod.

2017-06-06 20:24 UTC, colinschoen commented
Sure, think I will make the mod.

2017-06-06 23:10 UTC, jdarwood007 commented
We can spin up a new repo to contain the mod call it smf benchmark.  Contain it in there as a mod.  As a plus, allow us to easily call it from a benchmark.php as cron/cli.  So then us devs could pull down the mod and latest 2.1 dev, then have the cron script go through, running the benchmark and sending the results out (either in post or email).

2017-08-05 06:49 UTC, albertlast commented
@colinschoen what is the status of the mod?

2017-08-05 06:51 UTC, colinschoen commented
Low on the priority list. Planned but not started.

On Fri, Aug 4, 2017 at 23:49 albertlast <notifications@github.com> wrote:

> @colinschoen <https://github.com/colinschoen> what is the status of the
> mod?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/SimpleMachines/SMF2.1/pull/4088#issuecomment-320419622>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACysalsHnMfUe9PKIMin13Zs0BKsCGGsks5sVBBlgaJpZM4NvFNY>
> .
>

2017-08-23 21:39 UTC, albertlast commented
I was interesting how mod creation works in smf,
so i take this pr and created a mod: https://custom.simplemachines.org/mods/index.php?mod=4155
It's nice on the one side and on the other side it's pain.