Update Load.php
SimpleMachines/SMF pull request #4156
Opened 2017-06-25 14:06 UTC by Underdog-01

SQL column does not appear to have a default value of '' and/or NOT NULL resulting in a possible undefined log error.
I came across this issue on a test forum while accessing part of the admin section.

Signed-off-by: Underdog-01 <github.underdog@gmail.com>

2017-06-29 18:40 UTC, Sesquipedalian requested changes

2017-06-29 18:40 UTC, Sesquipedalian commented on Sources/Load.php
> +			if ((!empty($row['avatar'])) && $image_proxy_enabled && stripos($row['avatar'], 'http://') !== false)
What's the point of this change?

2017-06-29 18:42 UTC, Sesquipedalian commented
If the avatar column can be NULL, then we probably want to change the installer and upgrader files to make it a NOT NULL.

2017-06-29 23:24 UTC, Underdog-01 commented on Sources/Load.php
> +			if ((!empty($row['avatar'])) && $image_proxy_enabled && stripos($row['avatar'], 'http://') !== false)
To ensure the column has a value prior to using stripos .. I did not see an error from that line but put the edit in to cover the possibility as I have seen undefined errors with my own projects on similar logic. The brackets could go around the first 2 variables or your other suggestion I also thought of prior can be implemented which will cover any null possibility.

2017-06-29 23:37 UTC, Underdog-01 commented
I can implement:  ~ not null default '' ~ but prior to doing that I need to check/test that there is not an attempt to insert a null value anywhere in the current SMF 2.1 coding. I will test things out this weekend & implement the edits unless someone else reads this & beats me to it.

2017-06-29 23:47 UTC, jdarwood007 commented
There isn't a case where that can happen though as you just flipped the first 2 checks around and the strpos is the 3rd check.

2017-06-30 01:21 UTC, Sesquipedalian commented on Sources/Load.php
> +			if ((!empty($row['avatar'])) && $image_proxy_enabled && stripos($row['avatar'], 'http://') !== false)
As @jdarwood007 said below,

>There isn't a case where that can happen though as you just flipped the first 2 checks around and the strpos is the 3rd check.

This change doesn't actually do anything.

2017-06-30 04:12 UTC, Antes commented
extra txt.

2017-06-30 04:15 UTC, Sesquipedalian commented
This branch is kind of messed up now, @Underdog-01. If you don't mind, please make a fresh branch, reimplement your finalized changes in that, and then submit it as a new PR.

2017-06-30 04:15 UTC, closed without merging

2017-06-30 04:19 UTC, Underdog-01 commented
Agreed.. but it will have to be Friday evening.

2017-06-30 04:22 UTC, Sesquipedalian commented
No problem. Thanks.