added Fetch All to DB API
SimpleMachines/SMF pull request #4178
Opened 2017-07-05 19:03 UTC by albertlast

added $smcFunc['db_fetch_all'] to mysql and pg
could be use full where you try to proceed many row sets at once like the time topic: https://github.com/SimpleMachines/SMF2.1/pull/4165

2017-07-05 21:25 UTC, colinschoen requested changes

2017-07-05 21:25 UTC, colinschoen commented on Sources/Subs-Db-mysql.php
> +			'db_fetch_all'				=> 'smf_db_fetch_all',
The tabbing looks off.

2017-07-05 21:34 UTC, sbulen commented
Do we want the @s in the return statements?

I don't think we want errors ignored.  Also, none of the other simply called functions use it in that fashion, e.g., mysqli_get_server_info().  We should be consistent.

2017-07-06 03:20 UTC, albertlast commented
About the @ i see no consistency,
In Subs-Db-postgresql.php every fetch methode use @ 
and we don't ignore the error because of https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Load.php#L3047
when you like i can do in pg with @ and in mysql without,
but i don't see any reason for this...

2017-07-06 06:06 UTC, Oldiesmann commented
I'm not sure why we're suppressing errors for PostgreSQL, but we aren't for MySQL at all, so at the very least be consistent that way. We should look into why we are suppressing errors in PostgreSQL for the fetch functions though.

2017-07-10 04:17 UTC, merged