More phpDoc fixes
SimpleMachines/SMF pull request #4213
Opened 2017-07-22 21:25 UTC by Yoshi2889

Signed-off-by: Yoshi2889 <rick.2889@gmail.com>

2017-07-23 12:21 UTC, albertlast requested changes

2017-07-23 12:21 UTC, albertlast commented on Sources/Subs-Db-postgresql.php
> + * !!! Not sure what this is supposed to do.
Return the affected rows of a query.
see  http://php.net/manual/de/function.pg-affected-rows.php

2017-07-23 12:21 UTC, albertlast commented on Sources/Subs-Db-postgresql.php
> + * @param resource $connection = null The connection (if null, $db_connection is used) (not used here?)
The mysql version can use it:
https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/Subs-Db-mysql.php#L541

2017-07-31 17:36 UTC, colinschoen approved these changes
Pending albertlast's requested changes. LGTM

2017-07-31 18:06 UTC, merged