Css
SimpleMachines/SMF pull request #4237
Opened 2017-08-14 19:35 UTC by Gwenwyfar

Just some more details fixed/improved. A lot of edits, but these are mostly minor. Just getting these in before we start having conflicts.

2017-08-14 19:38 UTC, XinYenFon requested changes
Rest looks fine.

2017-08-14 19:38 UTC, Antes commented on Themes/default/css/index.css
> +* {
Well this is an important step, not that I'm against but requires some careful testing to be safe.

2017-08-14 19:38 UTC, Antes commented on Themes/default/css/index.css
> +	border-bottom-color: #346;
changes like this requires consistency, either go for all CSS or just revert it.

2017-08-14 19:46 UTC, Gwenwyfar commented on Themes/default/css/index.css
> +* {
Margin/padding should be fine, browser default ones are too inconsistent to be relied onto. Border-box could cause some harm, but at most it'll break somewhere that widths are used that conflict with padding, better to find those early and they're very easy to fix. I looked at a wide range of pages and didn't find any problems so far, other than the two already fixed.

2017-08-14 20:15 UTC, Gwenwyfar commented on Themes/default/css/index.css
> +	border-bottom-color: #346;
Let's leave it like that for now then.

2017-08-15 11:52 UTC, XinYenFon approved these changes

2017-08-16 11:47 UTC, XinYenFon approved these changes

2017-08-16 11:47 UTC, Antes commented on Themes/default/css/index.css
> +* {
Those type of padding issues can be fixed in RC period.

2017-08-16 16:28 UTC, frandominguezl approved these changes

2017-08-17 16:04 UTC, merged