Fixes #4011
SimpleMachines/SMF pull request #4245
Opened 2017-08-18 01:01 UTC by sbulen

If user selects to use SSL, ensures all URLs are https://. It does this by ensuring $boardurl is aligned with the SSL setting before setting any others, e.g., themes - everything else keys off of $boardurl.

Also ensures you cannot select SSL if you have no cert installed.

Further, ensures you MUST use SSL if you have an http:// => https:// redirect active.

If folks think it makes sense to add similar edits to the force_ssl setting in the admin control panel.

2017-08-18 01:03 UTC, sbulen commented
I had to revise & retest due to newly developed merge conflicts.  

FYI - I have tested:
  -  Windows & linux, both apache  (no IIS)
  -  With certs & without
  -  With redirects & without 
  -  With forums in subdirectories & not

That said, I can't test everything...  E.g., I haven't tested with subdomains.  

Any questions, let me know,

2017-08-19 03:50 UTC, colinschoen requested changes
Can you fix the doc block formatting.

2017-08-19 16:36 UTC, sbulen commented
Done.  Yep, they were ugly.

2017-08-25 19:47 UTC, colinschoen approved these changes
LGTM

2017-08-25 19:48 UTC, merged