Change BoardIndex Templates to be more flexible
SimpleMachines/SMF pull request #4310
Opened 2017-09-17 21:38 UTC by jdarwood007

This technically adds a feature, but this feature prevents modifications from needing to modify the template if they need to inject a "fake" board.  This also allows us to more easily handle redirects differently than boards.

@Antes You may want to review this.
@Gwenwyfar Antes thinks you may be interested.

Signed-off-by: jdarwood007 <unmonitored+github@sleepycode.com>

2017-09-17 21:44 UTC, XinYenFon approved these changes

2017-09-25 17:13 UTC, Sesquipedalian commented on Themes/default/BoardIndex.template.php
> + * Outs the board icon for a standard board.
Nit: "Outs the..." is weird English. This should probably be "Outputs the..." or (better) "Prints the..."

2017-09-25 17:16 UTC, Sesquipedalian requested changes
I like the approach. Just requesting a couple adjustments to the comments.

2017-09-25 17:16 UTC, Sesquipedalian commented on Themes/default/BoardIndex.template.php
> + * This gets hidden on mobile if $board['last_post']['id'] is empty by the main template.
Nit: this comment is unclear.

2017-09-26 01:49 UTC, jdarwood007 commented
Thanks, I like it as well.  SimpleDesk and other mods will be able to easily add "fake" boards now with custom content for the all the columns.  The code is easier to read as well and should be easier on theme developers to make changes to it.

Updated the comments.

2017-09-26 17:35 UTC, Sesquipedalian approved these changes

2017-09-26 17:36 UTC, merged