Attachments total amount and size
SimpleMachines/SMF pull request #4436
Opened 2017-12-25 21:27 UTC by MissAllSunday

fixes #4386
fixes #4385

Adds back the events for canceled and maxfilesexceeded
Updates Dropzone to 5.2.0

2017-12-26 00:20 UTC, MissAllSunday commented
It seems I borked Scrutinizer...  110 minutes performing "PHP Analyzer: Running Analysis" and counting...

2017-12-26 13:23 UTC, d3vcho commented
+14h running now xD

2017-12-28 16:28 UTC, MissAllSunday commented
OK that didn't work...

2018-01-01 06:05 UTC, colinschoen commented
Will review soon.

2018-01-02 03:24 UTC, colinschoen commented
I am still able to upload more files than the max amount. Is this working for you locally?

2018-01-08 22:15 UTC, MissAllSunday commented
did couple of tests but will check it again.

2018-02-13 06:01 UTC, colinschoen commented
Bump... :)

2018-03-05 07:17 UTC, colinschoen requested changes
Marking as needs attention so this isn't still pending my review. PTAL when able.

2018-03-09 16:46 UTC, MissAllSunday commented
sorry, my PC died out and I haven't had the time to setup a proper dev env.

2018-03-13 02:14 UTC, colinschoen commented
No worries. Any chance you will have time to work on this in the near future?

2018-03-18 01:11 UTC, MissAllSunday commented
OK, I believe I got all the checks covered, theres still the multi-file select issue but I'm afraid thats a limitation of the plugin itself and haven't had found a way around it,

2018-04-15 05:37 UTC, colinschoen approved these changes
LGTM nice work

1 spelling nit

2018-04-15 05:37 UTC, colinschoen commented on Themes/default/scripts/smf_fileUpload.js
> +			// Check againts the max amount of files setting
nit: againts -> against

2018-05-13 18:28 UTC, merged