Dont proxy images for bots, fixes #4448
SimpleMachines/SMF pull request #4503
Opened 2018-01-22 00:49 UTC by sbulen

Don't proxy images for bots.  

This fixes issues where site recrawls, even by good bots like Google, can cause your cache to grow by many GB of data & get completely randomized - useless as a cache.   

Also, bots probably should "see" the image's proper link anyway.  Give the image's original source page proper credit.

At this point in time, Google does not penalize sites for mixed-content pages (http & https), so this will not hurt Google's ranking of your forum's content.

2018-01-22 04:38 UTC, Sesquipedalian requested changes

2018-01-22 04:38 UTC, Sesquipedalian commented on Sources/Subs.php
> +						return;
This should go inside the `if ($image_proxy_enabled)` block.

2018-01-22 04:38 UTC, Sesquipedalian commented on Sources/Subs.php
> +						return;
This should go inside the `if ($image_proxy_enabled)` block.

2018-01-22 06:41 UTC, sbulen commented
I'll make the change & retest.

2018-01-23 03:41 UTC, sbulen commented
Done.  Tests OK.
Tested on a wamp server, php5.6, MySQL 5.7.

2018-01-23 07:23 UTC, Sesquipedalian approved these changes

2018-01-23 07:24 UTC, merged