Added support for external image proxy
SimpleMachines/SMF pull request #4565
Opened 2018-02-24 13:46 UTC by albertlast

By reading this: https://www.simplemachines.org/community/index.php?topic=558946.0
and see that different solution exists ( https://github.com/willnorris/imageproxy) which all need the data in same way:  proxy_url + image_url
And noticing that the amount of changes not high i decide to add this feature offical

What it do:
- add a second level of image proxy = 0 is disable 1 is proxy.php 2 is external proxy
- fix a docu issue $image_proxy_enabled is everywhere a int and not a bool
- add $image_proxy_url

external proxy works only when you switch the mode to 2 AND the $image_proxy_url is not empty otherwise the smf use proxy.php.

2018-02-24 22:46 UTC, Sesquipedalian commented
I haven't tested, but this looks pretty good. Can I get you to adjust the admin interface in ManageServer.php's `ModifyGeneralSettings()` in order to support this?

2018-02-25 07:44 UTC, albertlast commented
As expected the gui addition takes more time as the technical stuff,
reason why i hold this back until i got a go from your side.

2018-03-08 04:39 UTC, Sesquipedalian requested changes
Two fixes and a suggestion for better help text.

2018-03-08 04:39 UTC, Sesquipedalian commented on Sources/Load.php
> +					$row['avatar'] = $image_proxy_url . $row['avatar'];
```
$row['avatar'] = $image_proxy_url . urlencode($row['avatar']);
```

2018-03-08 04:39 UTC, Sesquipedalian commented on Themes/default/languages/Help.english.php
> +$helptxt['image_proxy_url'] = 'Needs to be maintained with the proxy url, when empty the internal proxy will be used';
This needs some more descriptive help text. I suggest this:
```
Enter the URL for your external proxy <strong>exactly</strong> the way it should be accessed for the image file.<br><br>For example, if your proxy serves files via <code>http://www.example.com/yourproxy.php?file=[URL of proxied file]</code>, enter <code>http://www.example.com/yourproxy.php?file=</code> here.<br><br>If this field is left empty, SMF's internal proxy will be used.
```

2018-03-08 04:39 UTC, Sesquipedalian commented on Themes/default/languages/ManageSettings.english.php
> +$txt['image_proxy_url'] = 'URL of external Image Proxy';
'URL of external image proxy' ← lowercase

2018-03-08 04:41 UTC, Sesquipedalian requested changes
One more requested change that I meant to include in the previous review.

2018-03-08 04:41 UTC, Sesquipedalian commented on Sources/Load.php
> +					$user_settings['avatar'] = $image_proxy_url . $user_settings['avatar'];
```
$row['avatar'] = $image_proxy_url . urlencode($user_settings['avatar']);
```

2018-03-08 06:13 UTC, Sesquipedalian commented
dc464c6 missed the other urlencode that we need. :)

2018-03-08 06:26 UTC, albertlast commented
nope the others are already urencode?

2018-03-08 06:33 UTC, Sesquipedalian commented
[This one](https://github.com/SimpleMachines/SMF2.1/pull/4565/files#diff-e44bf29380cd171e044f5bf3ac967c8dR1277).

2018-03-08 08:06 UTC, albertlast commented
okay i miss this one...
will i change later this day

2018-03-08 10:28 UTC, albertlast commented
done

2018-03-08 11:10 UTC, Sesquipedalian approved these changes

2018-03-08 11:11 UTC, merged

2018-03-09 15:13 UTC, albertlast commented
By thinking of that what we done,
was the urlencode a bad idea.
Why you wanted to urlencode @Sesquipedalian ?