Check $cur_profile['email_address'] before used
SimpleMachines/SMF pull request #4569
Opened 2018-02-26 17:14 UTC by albertlast

Well to create this issue you had to activate "send_validation_onChange"
but even than i was not fully able to reproduce this error but this should solve this any way.

related issue: https://www.simplemachines.org/community/index.php?topic=559067.0

2018-02-26 17:41 UTC, Sesquipedalian requested changes
Copy/paste error?

2018-02-26 17:41 UTC, Sesquipedalian commented on Sources/Profile-Modify.php
> +		if (this.email_address.value != "'. (!empty($cur_profile['email_address']) ? !empty($cur_profile['email_address']) : '') . '")
I think you probably meant to write this:
```
(!empty($cur_profile['email_address']) ? $cur_profile['email_address'] : '')
```

2018-02-26 17:50 UTC, Sesquipedalian approved these changes

2018-02-26 17:50 UTC, merged

2018-02-26 23:46 UTC, jdarwood007 commented
Whats the error here?  email is a requirement of all profiles, so not sure how you are getting a blank email to trigger this.

2018-02-27 01:16 UTC, smfbigguy commented
People were trying to register on my site. I could see them. When they did I would get the error I posted on SMF. After I applied the fix I was able to register perfectly. I have seen this happening on my site for about 4 or 5 days. Numerous people generated that error. That is all I can tell you really.

2018-02-27 05:29 UTC, albertlast commented
In this moment when the user accept the licence(in the regestry process) the profile stuff is builded up,
but at this moment the user didn't provide any mail information.