Updates SCEditor to version 2.1.2
SimpleMachines/SMF pull request #4576
Opened 2018-02-28 22:18 UTC by Sesquipedalian

Fixes #4567 

The main thing this PR does is in the title. Additionally, it does the following:

1. Moves the setup for the SCEditor options from GenericControls.template.php to Subs-Editor.php, and adds a hook to access them.

2. Some other minor fixes related to displaying the editor.

3. Some cleanup on the sadly neglected personal message authoring template. (This was incidental to the purpose of this PR, but oh well.)

2018-03-08 16:03 UTC, Antes commented
Certain items originally used by SCEditor still missing from SMF version. Is there any chance you can work on them ?

* Justify (very important for academics imo)
* [YouTube](https://www.sceditor.com/documentation/plugins/autoyoutube/) (because why not it has core module support already)
* Full-Screen (aka maximize) which is very useful for academic and long-posting sites (tho this might require live-preview to be more complete)
* Cut/Copy/Paste
* [Undo](https://www.sceditor.com/documentation/plugins/undo/)

2018-03-08 16:48 UTC, Sesquipedalian commented
Agreed on all counts. :)

2018-03-08 19:11 UTC, Sesquipedalian commented
Oooooh dear. While looking into implementing those, I discovered that a big chunk of code in `create_control_richedit()` is a complete mess. Everything loop starting [here](https://github.com/SimpleMachines/SMF2.1/pull/4576/files#diff-a5187aaee5e88e55b9c81aa6b74cdcf7R1801) is a half-baked mishmash of code for the 2.0 editor and SCEditor that has barely been touched since 2012. I'm rather surprised the editor has been working at all. If we want localization of the editor to work or for mods to be able to do anything with it via the integration hook, I'm going to need to rip all that out and start over.

2018-03-08 19:15 UTC, Sesquipedalian commented
From what I can tell, the hope way back then was to try to create a backwards-compatible system so that BBC mods for 2.0 could be installed without changes on 2.1. I strongly doubt that this will be possible to maintain. I will do what I can, but as my signature on simplemachines.org says, **I promise you nothing.**

2018-03-09 12:07 UTC, Antes commented
If you are going for all in my list, this should help you on the live-preview (or at least ajax-preview); https://github.com/Archer70/CoreStore - I'm sure @Archer70 won't mind 😄

2018-03-10 09:51 UTC, Antes commented
Justify is not working.

2018-03-10 21:12 UTC, Archer70 commented
@Antes IIRC, the ajax preview on CoreStore was kinda hacked in there. Maybe not the best thing to copy. xD

2018-03-10 21:14 UTC, Antes commented
@Archer70 It`ll give the idea.

2018-03-12 01:32 UTC, Sesquipedalian commented
I'm wasn't planning on adding anything that goes beyond SCEditor's standard maximize behaviour.

2018-03-12 08:27 UTC, Antes commented
Notice: Undefined index: disabledBBC in ...\Sources\Post.php on line 1837
Notice: Undefined index: disabledBBC in ...\Sources\Post.php on line 1838
Notice: Undefined index: disabledBBC in ...\Sources\Post.php on line 1838

Commit: ((a716a1fca...))

2018-03-12 09:24 UTC, Antes commented
Notice: Undefined index: disabledBBC in ...\Sources\Subs-Editor.php on line 2029

Quick question; is it intentional that preview is not showing YouTube videos (just link).

2018-03-12 10:12 UTC, Sesquipedalian commented
> Quick question; is it intentional that preview is not showing YouTube videos (just link).

No. 66d0f20 should solve that. :)

2018-03-12 18:00 UTC, Antes commented
LGTM

2018-03-12 23:35 UTC, Sesquipedalian commented
Bleh. Unfortunately, the CSS on mobile screens needs some more work. The overall layout of the editor is broken, and YouTube videos are not responsive at all. Once I get a chance to fix that, this should be good to go.

2018-03-13 13:04 UTC, Antes commented
I still don't get the point of introducing two div containers, can't you simply limit the iframe with max-width ?

2018-03-13 18:00 UTC, Sesquipedalian commented
I tried that first, but it resulted in large amounts of white space below the video. The container div would still be the same height that it would have been if there were no max-width. Two layers of wrapping is apparently the only solution anyone has ever found to making an iframe responsive while also imposing a max-width on it.

2018-03-13 18:01 UTC, Sesquipedalian commented
If you have a more elegant solution, that'd be more than welcome.

2018-03-13 18:08 UTC, Antes commented
```
iframe {
	max-width: 100%;
}
```

works perfectly fine on my Lumia 820 & browser responsive tests. I do not see any scrolling.

2018-03-13 18:22 UTC, Sesquipedalian commented
Oh, I see the point of miscommunication now. Yes, if we want the video to expand to fill the entire available width, that's relatively easy and would not require a second wrapper element. But on large screens it can look a bit ridiculous if we don't set a max-width of a certain number of pixels. Unfortunately, setting something like `max-width: 560px` on the iframe itself or on the first level container element results in this:
![screen shot 2018-03-13 at 12 20 54 pm](https://user-images.githubusercontent.com/191731/37361642-0d6896fc-26b9-11e8-9dd7-d1f26f4d6bee.png)
Note the black bars at the top and the cropping at the sides.

2018-03-13 18:35 UTC, Antes commented
I just tested my changes on 27'' (1080p) screen its looking ok. Sure you can dictate some min-height/width say like width: 50% / height: 250px. More you increase the height more black space you get in your hand because of video's preview image.

2018-03-13 19:05 UTC, Sesquipedalian commented
> More you increase the height more black space you get

Exactly. In comparison, by using the two containers I get this result:

![screen shot 2018-03-13 at 12 59 58 pm](https://user-images.githubusercontent.com/191731/37363960-d5de552c-26be-11e8-950a-99bbeeb9feb0.png)
![screen shot 2018-03-13 at 1 00 21 pm](https://user-images.githubusercontent.com/191731/37363976-daa391bc-26be-11e8-8c18-6e49d19ece6e.png)
![screen shot 2018-03-13 at 1 00 41 pm](https://user-images.githubusercontent.com/191731/37363990-e2777ca0-26be-11e8-9802-012a420e176c.png)
![screen shot 2018-03-13 at 1 00 49 pm](https://user-images.githubusercontent.com/191731/37364002-e7647ac4-26be-11e8-975e-1e7cc27f1ff8.png)

No black bars, aspect ratio is always maintained correctly, and the iframe never grows to more than 560px wide on large screens.

2018-03-14 11:49 UTC, Gwenwyfar commented
You can use only one wrapping div in the iframe (and this is the usual way to make it responsive indeed). Just move max-width to the single div.

2018-03-14 17:55 UTC, Sesquipedalian commented
> You can use only one wrapping div in the iframe (and this is the usual way to make it responsive indeed). Just move all the code you have in the containers to the single div.

I tried doing that (see example 2 below), but I couldn't get it to produce the desired results. I am trying to get the results we see in example 4 below (i.e. the correct aspect ratio is maintained at all screen sizes and video never expands to wider than the max-width amount). If you know a way to achieve those results using only one container div, @Gwenwyfar, please do post it. I would love to get rid of the second container if that can be done while still getting the desired results. 🙂

---

# Example 1: One container div, with no max-width
## HTML:
```
<div class="videocontainer">
	<iframe frameborder="0" src="https://www.youtube.com/embed/UnPI4xKvf0c?wmode=opaque" data-youtube-id="UnPI4xKvf0c" allowfullscreen=""></iframe>
</div>
```
## CSS:
```
.videocontainer {
	position: relative;
	padding-bottom: 56.25%;
}
.videocontainer iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100% !important;
	height: 100% !important;
}
```
## Results:
Correct aspect ratio is maintained at all screen sizes, but video always expands to fill all available space.
### Large screen:
<img width="1356" alt="screen shot 2018-03-14 at 11 31 46 am" src="https://user-images.githubusercontent.com/191731/37420411-53026224-277c-11e8-9ef1-208f650a0b74.png">


### Smaller screens:
<img width="818" alt="screen shot 2018-03-14 at 11 39 46 am" src="https://user-images.githubusercontent.com/191731/37420455-6dd514de-277c-11e8-8675-e878ae04b8fc.png">


---

# Example 2: One container div, with max-width set on container
## HTML:
```
<div class="videocontainer">
	<iframe frameborder="0" src="https://www.youtube.com/embed/UnPI4xKvf0c?wmode=opaque" data-youtube-id="UnPI4xKvf0c" allowfullscreen=""></iframe>
</div>
```
## CSS:
```
.videocontainer {
	max-width: 560px;
	position: relative;
	padding-bottom: 56.25%;
}
.videocontainer iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100% !important;
	height: 100% !important;
}
```
## Results:
Video never expands to wider than the max-width amount, but correct aspect ratio is not maintained on larger screen sizes. 
### Large screen:
Iframe is the same height as it would be if there were no max-width. Black bars across the top and bottom. Left and right sides are cropped out.
<img width="1358" alt="screen shot 2018-03-14 at 11 07 02 am" src="https://user-images.githubusercontent.com/191731/37418448-dbc81b4e-2777-11e8-840b-118415fd2cf2.png">

### Smaller screens:
At this size and below, everything works nicely.
<img width="832" alt="screen shot 2018-03-14 at 11 08 11 am" src="https://user-images.githubusercontent.com/191731/37418588-2e46ccc6-2778-11e8-9b7d-a07493a2e52e.png">

---

# Example 3: One container div, with max-width set on iframe
## HTML:
```
<div class="videocontainer">
	<iframe frameborder="0" src="https://www.youtube.com/embed/UnPI4xKvf0c?wmode=opaque" data-youtube-id="UnPI4xKvf0c" allowfullscreen=""></iframe>
</div>
```
## CSS:
```
.videocontainer {
	position: relative;
	padding-bottom: 56.25%;
}
.videocontainer iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100% !important;
	height: 100% !important;
	max-width: 560px;
}
```
## Results:
Video never expands to wider than the max-width amount, but correct aspect ratio is not maintained on larger screen sizes.  Identical to previous example.
### Large screen:
<img width="1358" alt="screen shot 2018-03-14 at 11 07 02 am" src="https://user-images.githubusercontent.com/191731/37418448-dbc81b4e-2777-11e8-840b-118415fd2cf2.png">

### Smaller screens:
<img width="832" alt="screen shot 2018-03-14 at 11 08 11 am" src="https://user-images.githubusercontent.com/191731/37418588-2e46ccc6-2778-11e8-9b7d-a07493a2e52e.png">

---

# Example 4: Two container divs, with max-width set on outer div
## HTML:
```
<div class="videocontainer">
	<div>
		<iframe frameborder="0" src="https://www.youtube.com/embed/UnPI4xKvf0c?wmode=opaque" data-youtube-id="UnPI4xKvf0c" allowfullscreen=""></iframe>
	</div>
</div>
```
## CSS:
```
.videocontainer {
	max-width: 560px;
}
.videocontainer div {
	position: relative;
	padding-bottom: 56.25%;
}
.videocontainer iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100% !important;
	height: 100% !important;
}
```
## Results:
Correct aspect ratio is maintained at all screen sizes and video never expands to wider than the max-width amount.
### Larger screen:
<img width="1362" alt="screen shot 2018-03-14 at 11 28 32 am" src="https://user-images.githubusercontent.com/191731/37419783-da8d9c38-277a-11e8-8bbb-c8e436a6f9f4.png">

### Smaller screens:
<img width="823" alt="screen shot 2018-03-14 at 11 28 56 am" src="https://user-images.githubusercontent.com/191731/37419811-eadcbd80-277a-11e8-914b-907e5711ebb9.png">

2018-03-14 21:27 UTC, Gwenwyfar commented
Oh, you're right. It's the silly way percentages are calculated according to the parent width, and not their own (they don't get a lot of use for the same reason...)

2018-03-15 01:02 UTC, Sesquipedalian commented
@Gwenwyfar: Cool. :)

@colinschoen: This is done as far as I am concerned. Look good to you?

2018-03-15 01:07 UTC, colinschoen commented
I’ll take a look tonight. Thanks for all your work on this.

2018-03-15 05:43 UTC, colinschoen requested changes
Nit

Other than that, awesome work.

LGTM

2018-03-15 05:43 UTC, colinschoen commented on Sources/Subs.php
> +				'disabled_content' => '<a href="https://www.youtube.com/watch?v=$1" target="_blank" rel="noopener">https://www.youtube.com/watch?v=$1</a>',
This can just be `allowfullscreen` instead of `allowfullscreen=""` since it is a boolean attribute and the presence implies True.

2018-03-16 08:18 UTC, merged