Language
SimpleMachines/SMF pull request #4613
Opened 2018-03-11 17:17 UTC by Gwenwyfar

2018-03-11 19:02 UTC, Sesquipedalian requested changes
Small spelling error

2018-03-11 19:02 UTC, Sesquipedalian commented on Themes/default/languages/Search.english.php
> +$txt['spider_mode_note'] = 'Note that logging of every spider action only occurs if tracking is set to either "moderate" or "agressive". Detail of every spider\'s action is only logged if tracking is
Spelling: "aggressive"

2018-03-12 10:33 UTC, illori commented
if you want to fix another one...
`Your request has been submitted, please be patient while the request is considered..`

we dont need 2 periods at the end of this one

2018-03-12 10:42 UTC, illori commented
maybe one more?
`Thank you for submitting this report. You should hear back from the admin team shortly.`

IMO should be administration and leave out team completely.

2018-03-12 13:36 UTC, Gwenwyfar commented
Done. The first one had already been fixed, @illori.

2018-03-12 13:40 UTC, Gwenwyfar commented
Oh, the first one is an extra . in the template.

2018-03-12 23:43 UTC, Sesquipedalian approved these changes

2018-03-12 23:43 UTC, merged