Templates revision - part 3
SimpleMachines/SMF pull request #4629
Opened 2018-03-15 13:43 UTC by Gwenwyfar

Let's get this out before it grows into a little monster. There aren't many things left that will involve editing the templates from here onwards.

2018-03-17 00:18 UTC, equinoxmatt commented
Been looking at this for a short while tonight. I am not the best person to comment, but I took a look at your commits individually and checked your branch out. It seems fine, I can't see any issues.

I won't 'approve' it, because this isn't my area of expertise, but LTGM :+1:

2018-04-19 06:26 UTC, wintstar commented
@Gwenwyfar, the text in the reports is somewhat small.  Is there a way to make this a little bigger?
`index.php?action=admin;area=reports`

admin.css line 31
```
.table_caption, tr.table_caption td {
    color: #000;
    font-size: 10px;
    font-weight: bold;
}
```

2018-04-19 10:59 UTC, Gwenwyfar commented
This PR is already long enough, but I'll add font size revision to one of my next ones. There are some oddly sized fonts elsewhere as well.

2018-04-25 20:20 UTC, Sesquipedalian requested changes
Mostly just some changes regarding hyphenation and word wrapping.

2018-04-25 20:20 UTC, Sesquipedalian commented on Themes/default/css/calendar.css
> -	word-wrap: break-word;
Apparently, IE and Edge < 18 don't support the standard `overflow-wrap`, so we need to keep `word-wrap: break-word;` for them. 
https://caniuse.com/#search=overflow-wrap

2018-04-25 20:20 UTC, Sesquipedalian commented on Themes/default/css/index.css
> +	font-family: verdana, monospace, sans-serif;
This change doesn't make a lot of sense to me. If we define a generic `monospace` before the generic `sans-serif`, then the latter will never be used. So I think we only need one, right? Personally, I'd stick with `sans-serif` rather than `monospace` for this.

2018-04-25 20:20 UTC, Sesquipedalian commented on Themes/default/css/index.css
> -	word-wrap: break-word;
Because support for `hyphens` is dependent not only on browser, but also [on language](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Browser_compatibility), we should keep `word-wrap: break-word; overflow-wrap: break-word;` as a fallback.

2018-04-25 20:20 UTC, Sesquipedalian commented on Themes/default/css/index.css
> -	word-wrap: break-word;
As noted above, because support for `hyphens` is dependent not only on browser, but also [on language](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens#Browser_compatibility), we should keep `word-wrap: break-word; overflow-wrap: break-word;` as a fallback.

2018-04-25 20:20 UTC, Sesquipedalian commented on Themes/default/css/index.css
> +	word-break: break-all;
`word-break: break-all;` is not very nice to readers. It'd be better to use `hyphens: auto;` (with the vendor prefixes, of course).

2018-04-25 20:24 UTC, Sesquipedalian commented
Apparently GitHub doesn't allow comments on just any random line, so I couldn't add one for `#basicinfo h4` on line 2186 of index.css. That selector needs to have the following added to its ruleset in order to fix #4719:
```
word-wrap: break-word;
overflow-wrap: break-word;
-webkit-hyphens: auto;
-ms-hyphens: auto;
hyphens: auto;
```

2018-04-25 20:37 UTC, Sesquipedalian commented
I just noticed some other spots where `overflow-wrap` is being used without `word-wrap` being set as as compatibility fallback for IE. That should be fixed everywhere.

2018-06-05 14:15 UTC, Gwenwyfar commented
Just to update on this, I'm hoping to make the fixes soon, as I'm finally getting some free time back :)

2018-06-12 11:33 UTC, Antes commented
I think at this stage its better to just remove the conflict and merge this big one in and do rest of the fixes later.

2018-06-19 19:33 UTC, Gwenwyfar commented on Themes/default/css/index.css
> +	word-break: break-all;
Hyphens will not break some links and other long words. And unfortunately text-ellipsis needs white-space: nowrap which we also don't want here either.

2018-06-19 19:43 UTC, Gwenwyfar commented
Apparently GitHub doesn't allow comments on just any random line, so I couldn't add one for #basicinfo h4 on line 2186 of index.css. That selector needs to have the following added to its ruleset in order to fix #4719:

Why do you say both hyphens and break-all are needed? I'm noticing they don't work all that well together (either hyphens do not show up in some cases, and I've gotten another odd one where it divided all syllables into one line, that I can't seem to replicate again now)

2018-06-27 10:27 UTC, Sesquipedalian commented on Themes/default/css/index.css
> +	word-break: break-all;
If I can't convince you to use `hyphens: auto`, please at the very least use `word-wrap: break-word` instead of `word-break: break-all`. Using `word-wrap: break-word` will only break the word if absolutely necessary, whereas `word-break: break-all` will break any and all words whenever they reach the edge of the container.

2018-06-27 19:11 UTC, Gwenwyfar commented on Themes/default/css/index.css
> +	word-break: break-all;
You're right, I missed this.

2018-06-27 19:38 UTC, Sesquipedalian approved these changes

2018-06-29 01:55 UTC, Gwenwyfar commented
Can you handle the conflicts, Sesq? I could do it but it's going to also merge the PR (if there's another way through GitKraken I haven't it figured out yet)

2018-06-30 11:44 UTC, merged