Enabled PG convert html entities to utf8
SimpleMachines/SMF pull request #4690
Opened 2018-04-03 14:21 UTC by albertlast

Allow pg to convert html entities to utf8
since pg support the complet utf8 placed a check if mysql is used.

The if in 613 was for me a miracle,
so i try to convert this in a away which works.

The pg query are mimics mysql show queries.

2018-04-28 05:51 UTC, albertlast commented
@Sesquipedalian @colinschoen is there any issue with this pr?

2018-05-14 04:57 UTC, Sesquipedalian commented
> @Sesquipedalian @colinschoen is there any issue with this pr?

> colinschoen self-requested a review 29 days ago

I haven't looked at this since @colinschoen is planning to do it.

2018-05-27 17:35 UTC, albertlast commented
Since i see no move of colin i ask you to merge this pr.

2018-05-27 17:36 UTC, colinschoen commented
Thanks for the patience. I will review this as soon as I get back to the states in two days.

2018-06-11 04:22 UTC, albertlast commented
Could you find time to look into this?

2018-06-21 18:26 UTC, colinschoen requested changes

2018-06-21 18:26 UTC, colinschoen commented on Sources/ManageMaintenance.php
> +				SELECT column_name "Field",data_type "Type"
`nit`: Add space`"Field",data_type` -> `"Field", data_type`

2018-06-21 18:44 UTC, albertlast commented on Sources/ManageMaintenance.php
> +				SELECT column_name "Field",data_type "Type"
done

2018-06-21 18:44 UTC, colinschoen approved these changes
LGTM

Nice work

2018-06-21 18:45 UTC, merged