Mock as someone else when we do background task fixes #4753
SimpleMachines/SMF pull request #4754
Opened 2018-05-08 13:54 UTC by albertlast

the underlaying api expect that the curent user = the user is who get the stuff
The orginal issue: https://www.simplemachines.org/community/index.php?topic=559941.0
came from CreatePost_Notify_Background which is created when you mention someone for exp.

I'm not sure if the logic perfect...
but what it do -> check if the $user_info is the same how is targeting by this process,
when not we save the old one, get the new one process throw the process and resetet on the end to the old one.

Issue #4752

2018-05-11 18:25 UTC, Sesquipedalian approved these changes

2018-05-11 18:27 UTC, Sesquipedalian commented
Hm. According to the reporting user, these changes didn't fix the problem. I am a bit surprised by that.
https://www.simplemachines.org/community/index.php?topic=559941.msg3971785#msg3971785

Do you mind following up with him, @albertlast?

2018-05-11 20:56 UTC, albertlast commented
When you look at the line of code where the issue happen,
you notice that the issue is now a different one.

The new one get from register-notify

2018-05-13 07:45 UTC, albertlast commented
@Sesquipedalian maybe i was not fully clear, could you tell me what kind of user default value we got for non existing user?

2018-05-13 17:08 UTC, Sesquipedalian commented
> When you look at the line of code where the issue happen,
>you notice that the issue is now a different one.
>
>The new one get from register-notify

Yes, you are right. But that means the problem is unlikely to be missing info for guest users, since guests can't be sent notifications. It looks like there the time_format value is missing for an admin or a global moderator on the forum of the person who reported the bug. I'm not sure how that happened (I suspect that the person was mucking around in the database directly) but the best solution is probably just to make sure that all the required values are defined inside `timeformat()` itself.

2018-05-13 17:11 UTC, albertlast commented
timeformat is user dependent and
this why we're here with this pr.

2018-05-13 17:27 UTC, Sesquipedalian commented
> timeformat is user dependent and
> this why we're here with this pr.

Yes, but Register-Notify.php doesn't send anything to guests. It only sends things to members with the 		moderate_forum permission (see [here](https://github.com/SimpleMachines/SMF2.1/blob/release-2.1/Sources/tasks/Register-Notify.php#L31)). So the error must be happening for a member that has that permission but does not have a value set for `$user_info['time_format']` for some reason.

The code I've just submitted in #4759 should solve the immediate problem. However, I still also want to merge your code in 976885e. You are entirely right that we need to make sure we are using the correct set of `$user_info` data in `fetch_alerts()` so that we send the alerts with the correct time format. I don't think we need the code in d7a0c78, though, so if you could please revert that commit, then I will merge this PR and #4759.

2018-05-13 17:33 UTC, albertlast commented
Well i forgot the signed-off for the revert,
is this a issue?

2018-05-13 17:47 UTC, Sesquipedalian commented
> Well i forgot the signed-off for the revert,
is this a issue?

Amend the commit and force push it, and that should be fine.

2018-05-13 17:56 UTC, albertlast commented
rebase fix the issue.

2018-05-13 18:00 UTC, Sesquipedalian commented
Great.

2018-05-13 18:01 UTC, Sesquipedalian commented on Sources/Profile-View.php
> +		loadMemberData($memID, false, 'minimal');
Oh, I just noticed that you are calling `loadMemberData($memID, false, 'minimal')` here. It needs to be `loadMemberData($memID, false, 'profile')` in order to get the member's `time_format` value. That's probably why the errors were still happening.

2018-05-13 18:09 UTC, Sesquipedalian requested changes
Change 'minimal' to 'profile'

2018-05-13 18:13 UTC, albertlast commented
got fixed

2018-05-13 18:14 UTC, Sesquipedalian approved these changes

2018-05-13 18:29 UTC, merged