Update txt sentence
SimpleMachines/SMF pull request #4758
Opened 2018-05-13 14:55 UTC by MissAllSunday

Signed-off-by: Jessica González <suki@missallsunday.com>

2018-05-13 18:21 UTC, Sesquipedalian requested changes

2018-05-13 18:21 UTC, Sesquipedalian commented on Themes/default/languages/ManagePermissions.english.php
> +$txt['permissionhelp_lock'] = 'This permission allows an user to lock a topic. This can be done in order to make sure no one can reply to a topic. Only users with a \'Moderate board\' permission can
Actually, "a user" is correct. Because "user" is pronounced "you-ser," there is no need for the "n." Just another example of how English is weird.

2018-05-13 19:26 UTC, smfbigguy commented
The first part of the line you changed reads better. It should be changed to:

This permission allows a  user to lock a topic. This can be done in order to make sure no one can reply to a topic. Only users with a \'Moderate board\' permission can still post in locked topics.';

Sorry don't mean to be critical or anything it just reads better like this.

2018-05-13 19:28 UTC, smfbigguy commented on Themes/default/languages/ManagePermissions.english.php
> +$txt['permissionhelp_lock'] = 'This permission allows an user to lock a topic. This can be done in order to make sure no one can reply to a topic. Only users with a \'Moderate board\' permission can
Sorry I didn't see you posted below the code there.

2018-05-31 17:36 UTC, colinschoen approved these changes
LGTM

2018-05-31 18:02 UTC, merged