Added check for existing of file and line in backtrace class
SimpleMachines/SMF pull request #4802
Opened 2018-06-30 04:37 UTC by albertlast

While looking at the backtrace from https://github.com/SimpleMachines/SMF2.1/issues/4801
i notice the notice.
To evade them i place this checks.

This pr didn't fix the issue of the linked issue.

2018-07-01 10:42 UTC, frandominguezl requested changes

2018-07-01 10:42 UTC, d3vcho commented on Themes/default/languages/ManageMaintenance.english.php
> +$txt['unknown'] = 'unknown';
$txt['unknown'] already exists in Admin.english.php

2018-07-03 20:34 UTC, albertlast commented
Yeah was no need ther for this txt.

2018-07-04 10:54 UTC, Sesquipedalian approved these changes

2018-07-04 10:54 UTC, merged