More css fixes
SimpleMachines/SMF pull request #4813
Opened 2018-07-04 01:34 UTC by Gwenwyfar

2018-07-04 09:09 UTC, XinYenFon approved these changes

2018-07-08 14:00 UTC, XinYenFon approved these changes

2018-07-08 14:00 UTC, Antes commented on Themes/default/css/index.css
> +.cat_bar + .windowbg2, .cat_bar + .windowbg, .cat_bar + .roundframe {
I'm just curious related to this and missing .information + .windowbg/2 rest is nice ^^

2018-07-08 23:06 UTC, Antes commented on Themes/default/Calendar.template.php
> +			<tr class="', $alt ? 'windowbg' : 'windowbg', '">
:P

2018-07-09 09:16 UTC, XinYenFon requested changes
You also need to clean up the $alt definitions from removed functions.

2018-07-09 14:10 UTC, Gwenwyfar commented
You're aware that entire section is the clock easter egg right?

2018-07-09 15:21 UTC, Antes commented
Not really :P I just checked the code 😆 not the func.

2018-07-13 21:47 UTC, jdarwood007 commented
Quick testing shows nothing I see as breaking.  Antes gave a thumbs up as well

2018-07-13 21:47 UTC, merged