Possible fix for the double menu
SimpleMachines/SMF pull request #4885
Opened 2018-08-01 19:10 UTC by MeTiroAtuTia

I came up with this idea to try to solve #4882 

Let me know what you think

2018-08-02 03:54 UTC, albertlast commented
From technical side you got here the same issue like the other pr,
the end of line got changed.

2018-08-02 11:43 UTC, Gwenwyfar commented on Themes/default/index.template.php
> +				<div id="mobile_user_menu" class="popup_container menu_popup_container">
Can you use only one main class in the container here? Cleaner html this way (without the menu_popup_heading, etc)

2018-08-02 11:45 UTC, Gwenwyfar requested changes
There's also a leftover padding from .popup_window in desktop view, needs to be removed.

2018-08-02 11:45 UTC, Gwenwyfar commented
Thanks for doing this. Only fixes the main menu though, could you do the submenus also?

2018-08-02 16:37 UTC, MeTiroAtuTia commented
I fixed it I think it's fine now.
I didn't know the genericmenu uses the double menu as well, I'll have a look at it later today

2018-08-05 17:18 UTC, jdarwood007 commented
Can you fix the line endings please?

2018-08-05 17:31 UTC, MeTiroAtuTia commented
Sure, once I finish the genericmenu.

2018-08-06 05:17 UTC, DiegoAndresCortes commented
Fixed and updated for genericmenu

2018-08-06 05:23 UTC, DiegoAndresCortes commented
By the way, I forgot to mention that I decided to put the html code that wraps the function outside just in case a themer wants to easily replace/remove it, which is very likely.

2018-08-10 23:18 UTC, Gwenwyfar approved these changes

2018-08-10 23:19 UTC, merged