Improve secret q/a by using a more modern hashing method.
SimpleMachines/SMF pull request #4993
Opened 2018-09-02 23:02 UTC by jdarwood007

Fixes #3117 by using hash_password.  We do not convert old answers as we have no way to verify them.  We accept both md5 and hash_password_verify.  Due to the varying lengths of the two methods, we don't need to try and figure out the length first.  This doesn't attempt to convert the secret question upon successful answers.

2018-09-08 08:55 UTC, Sesquipedalian requested changes

2018-09-08 08:55 UTC, Sesquipedalian commented on Sources/Reminder.php
> +	if ($row['secret_question'] == '' || $row['secret_answer'] == '' || (!hash_verify_password($row['member_name'], $_POST['secret_answer'], $row['secret_answer']) && md5($_POST['secret_answer']) != $ro
Please add a comment to explain to future developers that the md5 check is there for the sake of backwards compatibility with old stored values.

2018-09-08 15:56 UTC, jdarwood007 commented
Added a nice big comment explaining it all.

2018-09-09 00:23 UTC, Sesquipedalian approved these changes

2018-09-09 00:23 UTC, merged