Dont overwrite the subboard posttime when it's newer fixes #5017
SimpleMachines/SMF pull request #5018
Opened 2018-09-22 14:27 UTC by albertlast

issue: #5017

2018-09-23 15:17 UTC, albertlast commented
The pr fixed the issue: https://www.simplemachines.org/community/index.php?topic=562333.msg3989423#msg3989423

beside of fixing the issue i align the cte query with the normal query, by droping the root board

2018-09-26 04:21 UTC, albertlast commented
@Sesquipedalian this pr is done, i would recomand based on the issue, that this got included into rc1.

2018-10-09 21:40 UTC, Sesquipedalian requested changes
This looks pretty good. There are two lines where you can remove some unnecessary calls to `forum_time()`, and then it'll be ready to merge.

2018-10-09 21:40 UTC, Sesquipedalian commented on Sources/Subs-BoardIndex.php
> +				if (forum_time(true, $row_boards[$row_board['id_parent']]['poster_time']) < forum_time(true, $row_board['poster_time']))
I don't think you need to call `forum_time()` here. Just use the raw poster_time values.

2018-10-09 21:40 UTC, Sesquipedalian commented on Sources/Subs-BoardIndex.php
> +				&& forum_time(true, $row_boards[$row_board['id_parent']]['poster_time']) < forum_time(true, $row_board['poster_time']))
I don't think you need to call `forum_time()` here. Just use the raw poster_time values.

2018-10-10 03:41 UTC, albertlast commented
Fixed the unnessary calls

2018-10-10 08:12 UTC, Sesquipedalian approved these changes

2018-10-10 08:12 UTC, merged