use js to generate qr fixes #5000
SimpleMachines/SMF pull request #5078
Opened 2018-10-21 05:54 UTC by albertlast

used the fork of qrcode.js https://github.com/KeeeX/qrcodejs

change the url removed the google api call and removed the urlencode (dunno if we maybe need this)

someone need to test this.

issue #5000

2018-10-21 15:18 UTC, albertlast commented
@jdarwood007 the related issue is rc1 related...
so i'm not sure if than a good plane to set this pr as rc2

2018-10-21 15:19 UTC, jdarwood007 commented
Do you think we can get enough testing to ensure nothing breaks for RC1?

2018-10-21 15:22 UTC, albertlast commented
how ever decided to make the issue rc1,
was thinking that i guess.

but i got no test env for this here,
so i can't test this pr.

I only want to see that rc1 get released so i created some pr for the open rc1 issues.

2018-10-21 16:18 UTC, jdarwood007 commented
I will move it over to RC1, @Sesquipedalian can move it to RC2 if needed.

2018-10-23 22:23 UTC, Sesquipedalian commented
When I go to `?action=profile;area=tfasetup`, no QR code is shown. The JavaScript error log reports the following:
```
[Error] ReferenceError: Can't find variable: QRCode
	Global Code (index.php:391)
```
 It appears that the JavaScript isn't being loaded correctly.

2018-10-23 22:23 UTC, Sesquipedalian requested changes
The JavaScript does not appear to be loading correctly.

2018-10-23 22:26 UTC, Sesquipedalian commented on Themes/default/Profile.template.php
> +	loadJavaScriptFile('qrcode.js', array('force_current' => false, 'validate' => true));
This is probably the issue. As a rule, `loadJavaScriptFile()` needs to be called in the source files, not the template files.

2018-10-26 15:57 UTC, albertlast commented on Themes/default/Profile.template.php
> +	loadJavaScriptFile('qrcode.js', array('force_current' => false, 'validate' => true));
Should i call this in a different way or
move the call to the source file?

2018-10-26 18:58 UTC, Sesquipedalian commented on Themes/default/Profile.template.php
> +	loadJavaScriptFile('qrcode.js', array('force_current' => false, 'validate' => true));
Just move that call to the source file. 🙂

2018-10-27 06:24 UTC, albertlast commented
So i move the logic,
please test again.

2018-10-27 07:23 UTC, albertlast commented
Sorry i didn't notice that sesqui provide the action url,
by using index.php?action=profile;area=tfasetup
i get now a qr code shown which my phone reconized as 2fa code -> the 2fa app open.

2018-10-30 19:38 UTC, Sesquipedalian approved these changes

2018-10-30 19:39 UTC, Sesquipedalian commented
This works very nicely. 👍

2018-10-30 19:39 UTC, merged