Random compat 2.0.17
SimpleMachines/SMF pull request #5138
Opened 2018-11-11 17:32 UTC by MissAllSunday

Moves random_compat() files to their own folder on Sources/

2018-11-11 17:58 UTC, albertlast commented
Maybe you should read the related https://github.com/SimpleMachines/SMF2.1/pull/5077,
before wasting your time on idea which got already decline by the smf dev team.

2018-11-13 04:33 UTC, Sesquipedalian commented
> Maybe you should read the related #5077,
before wasting your time on idea which got already decline by the smf dev team.

😕 When was it rejected? I thought you just put it there because that's what you decided to do.

2018-11-13 04:40 UTC, Sesquipedalian commented
@MissAllSunday, to fix the Travis build failures, you'll need to add some appropriate regexes [here](https://github.com/SimpleMachines/BuildTools/blob/master/check-smf-license.php#L48). Then we should be able to merge this.

2018-11-13 05:01 UTC, albertlast commented
> 
> 
> > Maybe you should read the related #5077,
> > before wasting your time on idea which got already decline by the smf dev team.
> 
> 😕 When was it rejected? I thought you just put it there because that's what you decided to do.
> 
> EDIT: Oh, I see. Originally you had the library file separate, and then @jdarwood007 asked if it could be moved into Subs-Compat.php. That was probably the wrong idea on his part. Having it separate like your original idea and like @MissAllSunday is doing in this PR is better for long term maintenance. If I'd thought more about it at the time, I probably would have suggested that too, rather than cramming the whole library into one file like I suggested before.

You forced me to do two stupid things,
one throw everything one file and
secondly call the reloadsetting in context of the upgrade process -.-

2018-11-13 05:24 UTC, Sesquipedalian commented
Well, what I said was that we needed to include all the library functions, not just one that depends on others that weren't included. And then I was the one who compiled the library functions into a single block of code and gave it to you so that you could paste it into the file. So it's not like you did much work there, and thus you don't have much to complain about if we change our minds after further consideration.

Besides which, I'm not sure why you are acting so grumpy and rude about this anyway. Everyone's code gets changed sooner or later. That's the way this works. If you find yourself getting upset by that, perhaps there are some anger issues that you need to work on?

2018-11-13 05:56 UTC, albertlast commented
This had nothing to do with anger,
i mention four times,
that it's a bad idea to place the reloadsetting into the upgrade(specialy with the background we want to release rc1).

2018-11-13 18:04 UTC, Sesquipedalian commented
Indeed you did. And then #5124 was merged. So what exactly are you complaining about here?

2018-11-13 21:57 UTC, Sesquipedalian commented
@MissAllSunday, please also include the necessary changes in install.php and upgrade.php.

2018-11-13 21:58 UTC, Sesquipedalian requested changes
Please also include the necessary changes in install.php and upgrade.php.

2018-11-26 18:56 UTC, albertlast commented on other/upgrade.php
> +            if (!is_callable('random_int'))
The code is not well aligned -> because you use space and the code is using tab here.

2018-11-26 18:56 UTC, albertlast commented on other/install.php
> +            if (!is_callable('random_int'))
The code is not well aligned -> because you use space and the code is using tab here.

2018-12-22 07:22 UTC, merged