Handle spaces that are already encoded
SimpleMachines/SMF pull request #5174
Opened 2018-11-26 03:33 UTC by sbulen

Fixes #5170 .   The image proxy was having issues with URLs that contained %20.  

I considered two solutions, the first was to simply remove the call to iri_to_url() from proxy.php.  That felt safest, and produced the same results during image proxy tests.  

But this solution is more in line with the intent of using iri_to_url() - to cleanse & standardize url usage.

Tested on both WAMP & Linux.  Solves a # of dropped image issues with the image proxy.

2018-11-26 04:22 UTC, albertlast commented
Would it be not better to decode the url in general?

2018-11-26 21:21 UTC, sbulen commented
I agree this feels incomplete...  But putting a decode immediately before the encode (the next line of code) isn't a good approach either.  You might as well drop both.  

The root cause of the issue here is that this function assumes the content is not encoded.  But it frequently is encoded.  The vast majority of the time, folks are copying the string from a url or a 'share link' or a 'copy image address' from their browser.  

I'll try a different approach...

2018-11-26 22:12 UTC, albertlast commented
Looks for me not right,
you only look if possible one escape encoded char exists.
But it make not clear if the complete url ist encoded.

What would be hapen when you decode a non encoded url?

2018-11-26 22:21 UTC, sbulen commented
The problem here is that encoding *any* already-encoded character mangles that character.  Eg, %20 is becoming %2520, and %25 would become %2525, etc.  

There is no definitive way to determine if the url has already been encoded or not.  

This latest approach leaves the string alone if it finds something that looks like %99.  A very conservative approach.

2018-11-27 02:02 UTC, sbulen commented
How's this? 

At the same time, it feels a little more purist though a little more dangerous...  It feels like excessive processing of these URLs, which have been user-specified & have probably been copied from somewhere.  If we see more dropped pix caused by this processing, I'd suggest removing the call to iri_to_url() from proxy.php altogether.  

But this does work.  I have confirmed it fixes both #5170 & #5171 on both WAMP & Linux.

2018-11-30 05:10 UTC, sbulen commented
The above didn't work.  As suspected, we likely shouldn't even do the call to iri_to_url().   

More test data:

Photo: 6
http://www.guitarmachine.com/Home%20page%20white%20photo.jpg
[img]http://www.guitarmachine.com/Home%20page%20white%20photo.jpg[/img]
==================================================================================================
Photo: 40
http://www.ovationgallery.com/Gallery%20Storm/OG-storm-to-nutv-01.jpg
[img]http://www.ovationgallery.com/Gallery%20Storm/OG-storm-to-nutv-01.jpg[/img]
==================================================================================================
Photo: 41
http://www.itcelectronics.com/images/products/PHL%2030-10002.jpg
[img]http://www.itcelectronics.com/images/products/PHL%2030-10002.jpg[/img]
==================================================================================================
Photo: 50
http://i145.photobucket.com/albums/r227/Netskenmac/Roland%20Mobile%20Cube%20Amp/AmpMeasuringTape2.jpg
[img]http://i145.photobucket.com/albums/r227/Netskenmac/Roland%20Mobile%20Cube%20Amp/AmpMeasuringTape2.jpg[/img]
==================================================================================================
Photo: 179
http://www.midiguitar.net/group/EV-5%20Info/ev-5-schematics.png
[img]http://www.midiguitar.net/group/EV-5%20Info/ev-5-schematics.png[/img]
==================================================================================================
Photo: 181
http://3.bp.blogspot.com/--4xvZoFVOPM/TYGaGTaOkAI/AAAAAAAAADU/7EV8tjJy6WE/s400/DSCN1435%2B%25282%2529.JPG
[img]http://3.bp.blogspot.com/--4xvZoFVOPM/TYGaGTaOkAI/AAAAAAAAADU/7EV8tjJy6WE/s400/DSCN1435%2B%25282%2529.JPG[/img]
==================================================================================================

2018-12-10 09:22 UTC, Sesquipedalian requested changes

2018-12-10 09:22 UTC, Sesquipedalian commented on proxy.php
> -		$request = iri_to_url($request);
Don't remove this line. Instead, all you should need to do is change it to:
```
$request = iri_to_url(rawurldecode($request));
```

2018-12-11 00:40 UTC, Sesquipedalian commented on proxy.php
> -		$request = iri_to_url($request);
Disregard my previous comment. The issue was just that iri_to_url() wasn't correctly handling double-encoded `%` characters. #5194 fixes it properly.

2018-12-11 00:40 UTC, closed without merging