Code BBC max height fix
SimpleMachines/SMF pull request #5407
Opened 2019-02-10 12:53 UTC by SychO9

Fixes #5318

2019-02-10 21:19 UTC, live627 commented
So what happens with a one-liner?

And jquery? I personally dislike jquery, but hey I'm probably the odd one out so sue me.

2019-02-10 22:07 UTC, SychO9 commented
> So what happens with a one-liner?
well the "Expand" button is hidden by default, the jquery code checks if the code's height exceeds the maximum height which is set and if so shows the button, so a one liner wouldn't have the button to expand.

> And jquery? I personally dislike jquery, but hey I'm probably the odd one out so sue me.
well... ¯\_(ツ)_/¯

2019-02-12 18:38 UTC, Sesquipedalian requested changes

2019-02-12 18:38 UTC, Sesquipedalian commented on Sources/Subs.php
> +				'content' => '<div class="codeheader"><span class="code floatleft">' . $txt['code'] . '</span> <a class="codeoperation smf_select_text">' . $txt['code_select'] . '</a> <a class="codeoperation smf
Please add the same changes to the other version of the [code] BBC on this line:
https://github.com/SimpleMachines/SMF2.1/blob/1058026d83229306ce1b9999f3eb17fd0eef5e64/Sources/Subs.php#L1344

2019-02-12 23:44 UTC, Sesquipedalian approved these changes

2019-02-13 03:27 UTC, merged