Prevent ad block plus from hiding the like button
SimpleMachines/SMF pull request #5440
Opened 2019-02-16 07:01 UTC by live627

2019-02-16 09:11 UTC, SychO9 commented
ad block plus ? what's that

2019-02-19 01:05 UTC, Sesquipedalian commented
Using a different class name would be better than using none at all. Maybe "smflikebutton" would get past AdBlock?

2019-02-19 02:07 UTC, Sesquipedalian requested changes
Using a different class name would be better than using none at all. Maybe "smflikebutton" would get past AdBlock?

2019-02-19 04:34 UTC, Sesquipedalian approved these changes

2019-02-19 04:35 UTC, merged