optimize/speed up some queries in ip tracking
SimpleMachines/SMF pull request #5489
Opened 2019-03-08 01:47 UTC by live627

ref https://www.simplemachines.org/community/index.php?topic=565147.0

2019-03-08 03:34 UTC, jdarwood007 commented
Could we avoid using raw format here?

2019-03-08 03:56 UTC, live627 commented
no, why?

On Thu, Mar 7, 2019 at 8:34 PM Jeremy D <notifications@github.com> wrote:

> Could we avoid using raw format here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimpleMachines/SMF2.1/pull/5489#issuecomment-470792828>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAaWt3qO8n9ic-LdeE3PX91K31D-MkR5ks5vUdpNgaJpZM4bkeYX>
> .
>

2019-03-08 05:11 UTC, albertlast requested changes
Change the alias to b or create a new query_see_message would be mutch more cleaner way in my eyes-
And i like to see what the diff is between  * and id_msg

2019-03-08 05:11 UTC, albertlast commented on Sources/Profile-View.php
>  		FROM {db_prefix}messages AS m
Change the alias here from m to b would be better,
as you raw version.

2019-03-08 05:11 UTC, albertlast commented on Sources/Profile-View.php
> +		SELECT COUNT(id_msg)
The most benefit you got by changing the join,
how mutch is the time dif here when you change from id_msg to * ?

2019-03-08 05:11 UTC, albertlast commented on Sources/Profile-View.php
>  		FROM {db_prefix}messages AS m
Again change this to b would be better as the raw way.

2019-03-08 05:28 UTC, albertlast commented
I like the base idea to throw out boards join where is not needed,
but he way i don't like.

2019-03-09 00:12 UTC, jdarwood007 commented
@live627 ,

Raw should be avoided if at all possible.  Its bypassing all the security checks that we do in queries when processing the string.  Not that the string you are using shouldn't already be clean, just safer to avoid usage of this to ensure we don't open up any security holes by assuming the data is cleaned already.  The PR by @albertlast seems like it will do this for us.

I think if this gets accepted, the changes by #5491 should include changing this and merging it as well.

2019-03-27 11:35 UTC, live627 commented
This now depends on #5491. Once that gets merged, this can go in.

2019-03-27 11:38 UTC, albertlast commented
I waiting a test from you id_msg vs * benchmark. 
Because the SQL code get awkward,
It's should provide any benefit

2019-03-27 12:23 UTC, live627 commented
you already saw it at https://www.simplemachines.org/community/index.php?msg=4009918

2019-03-27 12:24 UTC, albertlast commented
Based on the pr here,
i guess you not only change the column name you also changed the join stuff.

2019-03-27 19:55 UTC, live627 commented
the join was still there in that test

removing the join brought the query down to ~40ms

On Wed, Mar 27, 2019 at 5:24 AM albertlast <notifications@github.com> wrote:

> Based on the pr here,
> i guess you not only change the column name you also changed the join
> stuff.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimpleMachines/SMF2.1/pull/5489#issuecomment-477127993>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAaWtxfiUsZ2SnJLIzb43WDzvr-8KWYAks5va2MHgaJpZM4bkeYX>
> .
>

2019-03-27 20:27 UTC, albertlast commented
which mysql version you got?
And can you please post explain of this two queries?

2019-03-30 22:50 UTC, merged