Show in search only approved message when needed
SimpleMachines/SMF pull request #5539
Opened 2019-03-26 05:54 UTC by albertlast

The performance impact here is less big as expected.

Another suprise for me was,
that ``$modSettings['postmod_active'] && !allowedTo('approve_posts')``
was not enough.
Since the board manager can see now unapproval message too,
so i had to add him to the check.

2019-03-26 11:11 UTC, live627 requested changes
approve_posts is a board permission, meaning that you must build and check it differently. Example:

https://github.com/SimpleMachines/SMF2.1/blob/ed54e36517065b22151783a6b246347efa14e286/Sources/PostModeration.php#L61-L77

And then inject it into the query

https://github.com/SimpleMachines/SMF2.1/blob/ed54e36517065b22151783a6b246347efa14e286/Sources/PostModeration.php#L196

2019-03-26 12:06 UTC, albertlast commented
I don't get it,
maybe you want to create own pr.

2019-03-26 20:45 UTC, Sesquipedalian commented
The manage_boards permission should not be part of this logic. That permission does not give the ability to approve or disapprove of posts or topics.

2019-03-26 20:46 UTC, albertlast commented
but the manage_boards got the right to see them,
so he should be able to search them?

2019-03-26 20:57 UTC, Sesquipedalian commented
> but the manage_boards got the right to see them,
> so he should be able to search them?

No, he doesn't. Please see further discussion in #5534.

2019-04-30 14:10 UTC, albertlast commented
So i removed the manage_boards check.

2019-05-23 07:17 UTC, Sesquipedalian submitted a review, later dismissed

2019-05-24 04:31 UTC, albertlast commented
@Sesquipedalian can i close than this pr?

2019-05-25 15:16 UTC, Sesquipedalian commented
Sure

2019-05-25 15:16 UTC, closed without merging