Extra attributes for css/js file elements
SimpleMachines/SMF pull request #5606
Opened 2019-04-17 14:02 UTC by SychO9

Closes #5604

2019-04-17 18:29 UTC, Sesquipedalian requested changes

2019-04-17 18:29 UTC, Sesquipedalian commented on Sources/Subs.php
> +						echo ' ', $key, '="', $value, '"';
For better HTML5 output, you'll want to handle boolean values differently. This should do the job:

```
foreach ($js_file['options']['attributes'] as $key => $value)
{
	if (is_bool($value))
		echo !empty($value) ? ' ' . $key : '';
	else
		echo ' ', $key, '="', $value, '"';
}
```

2019-04-17 18:29 UTC, Sesquipedalian commented on Sources/Subs.php
> +					echo ' ', $key, '="', $value, '"';
See previous comment for advice on how to handle boolean attributes.

2019-04-17 22:16 UTC, Sesquipedalian approved these changes

2019-04-23 17:51 UTC, umairaziz1 commented
Bug

2019-04-23 23:35 UTC, Sesquipedalian commented
> Bug

Can you explain what you mean a little more fully, @umairaziz1?

2019-05-14 18:30 UTC, umairaziz1 approved these changes

2019-05-23 14:32 UTC, merged