Notify
SimpleMachines/SMF pull request #6024
Opened 2020-02-22 09:10 UTC by live627

Breaks out the user info loading routine so that it may be useful to the background task. Fixes #6022 
Also standardize the content links for the alerts.

(Most of these changes are whitespace so I can better see what I'm doing)

ref https://www.simplemachines.org/community/index.php?topic=571923.0
ref https://www.simplemachines.org/community/index.php?topic=571858.0

2020-02-22 18:25 UTC, albertlast requested changes
select coment is curcial, the others are only notes.

2020-02-22 18:25 UTC, albertlast commented on Sources/Profile-View.php
> +	$qb = array(
Why note any more in else part and
why the array() syntax instead of $qb[]?

2020-02-22 18:25 UTC, albertlast commented on Sources/tasks/CreatePost-Notify.php
> +				mem.*, ln.id_board, ln.id_topic, ln.sent,
to use * is always bad: https://stackoverflow.com/questions/3639861/why-is-select-considered-harmful

2020-02-22 18:25 UTC, albertlast commented on Sources/Load.php
> + * @return array
funny note: we always define an array as return,
but you don't know what format of this array is XD

2020-02-25 03:05 UTC, live627 commented
As much as I really want to unify the alerts, I'm going to hold off on this and try it again when we start on the new version.

2020-02-25 03:05 UTC, closed without merging