Long quotes
SimpleMachines/SMF pull request #6027
Opened 2020-02-23 18:52 UTC by MissAllSunday

Fixes #5881

Adds a new setting for allowing users to expand/shrink a long quote.

To avoid messing up with the actual quoted content, it separates the quote into two, the cite header and the rest, meaning it will  only show the cite header on collapsed and the entire quote on expanded.

![Screenshot from 2020-02-23 12-50-10](https://user-images.githubusercontent.com/3420756/75117882-1bf01700-563b-11ea-993f-2d05077ae087.png)

![Screenshot from 2020-02-23 12-51-11](https://user-images.githubusercontent.com/3420756/75117896-3629f500-563b-11ea-8bb5-e250c56fe2ce.png)

2020-02-23 23:47 UTC, live627 commented
Can it be similar to the code tag in that it shows the first few lines while collapsed? (No scrollbar needed I think)

2020-02-24 00:03 UTC, MissAllSunday commented
The code tag is just text which makes it easier to extract some of it and show a teaser when collapsed.  Unfortunately it is not that easy to do the same with a quoted post since it can have any number of DOM elements on it, making it a lot more difficult to reliable extract a part of it.

2020-02-24 00:29 UTC, live627 commented
Then use CSS max height and hidden overflow. Pretty sure that the code tag does that.

2020-02-24 00:40 UTC, MissAllSunday commented
hidden-overflow forces a scroll bar on the element which kinda defeats the purpose of collapsing the quote.

2020-02-24 01:07 UTC, MissAllSunday commented
OK now theres a teaser
![Screenshot from 2020-02-23 19-06-03](https://user-images.githubusercontent.com/3420756/75123709-9a66ac00-566f-11ea-9678-c4f7ede3cc6d.png)


Theres only one issue with multiquote I'm still trying to see how to solve it.

2020-02-24 01:58 UTC, MissAllSunday commented
It now gracefully handles multiquotes

![Screenshot from 2020-02-23 19-57-51](https://user-images.githubusercontent.com/3420756/75124764-dc472080-5676-11ea-8402-08c894a1b3dd.png)

2020-02-24 19:07 UTC, SychO9 commented
Since Antes is having some trouble in github, here's what he noticed while testing the PR:

> you get Shrink/Expand buttons even if the setting is set to 0

2020-02-26 22:57 UTC, Sesquipedalian requested changes
LGTM, except one little thing. 😉

2020-02-26 22:57 UTC, Sesquipedalian commented on Themes/default/languages/Admin.english.php
> +$txt['quote_expand_pixes_units'] = 'pixels';
Nit: please change this key to `quote_expand_pixels_units`. The `l` is missing.

2020-02-27 09:51 UTC, merged

2022-03-05 11:32 UTC, gevv commented
Hi,

Is this feature added? It doesn't work in the latest version.

2022-03-05 13:37 UTC, smfbigguy commented
It works on my site fine.

2022-03-05 15:43 UTC, gevv commented
For setting from the admin panel this is very good.

Thanks everyone.