Address MariaDB limitation in strict mode
SimpleMachines/SMF pull request #6096
Opened 2020-04-28 22:59 UTC by sbulen

Fixes #6094 

@dragomano - please test!

@albertlast - input welcome.  I felt the more narrow query in the subquery made more sense.  I did A/B tests with my biggest users & no noticeable difference.

2020-04-28 23:20 UTC, jdarwood007 commented on Sources/News.php
> +		) nis ON nis.id_pm = pm.id_pm
nitpick here but we have always used "AS" even though its not required, as we are verbose.  Should do that even for a sub select.

2020-04-29 03:17 UTC, dragomano commented
It works fine, thanks :)

2020-04-29 04:10 UTC, albertlast commented
my test env didn't got a big pm setup.. so i cant this from a performance pov.
Personaly i had tried before to solve this by using distinct
```
	$request = $smcFunc['db_query']('', '
		SELECT DISTINCT pm.id_pm, pm.msgtime, pm.subject, pm.body, pm.id_member_from, pm.from_name, ' . $select_id_members_to . ' AS id_members_to, ' . $select_to_names . ' AS to_names
		FROM {db_prefix}personal_messages AS pm
			INNER JOIN {db_prefix}pm_recipients AS pmr ON (pm.id_pm = pmr.id_pm)
			INNER JOIN {db_prefix}members AS mem ON (mem.id_member = pmr.id_member)
		WHERE pm.id_pm > {int:start_after}
			AND (
				(pm.id_member_from = {int:uid} AND pm.deleted_by_sender = {int:not_deleted})
				OR (pmr.id_member = {int:uid} AND pmr.deleted = {int:not_deleted})
			)
		ORDER BY pm.id_pm {raw:ascdesc}
		LIMIT {int:limit} OFFSET {int:offset}',

2020-04-29 04:45 UTC, sbulen commented
It performs well on my test copy of my prod forum.   

I think it's either COUNT DISTINCT *or* GROUP_CONCAT...  but we need the GROUP_CONCAT function, so distinct doesn't work:
https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html

It works in my (small) pg environment.

2020-04-29 04:54 UTC, albertlast commented
Okay didn't notice the group_concat...
from a technical pov is the subqery from you differently to orginal because of position of the order by.

Limit is affected by the order by,
so to spread them into different parts of the query could lead in a different result.

2020-04-29 05:16 UTC, sbulen commented
Correct.  GROUP BY doesnt necessarily sort.  I'll tweak it a bit tomorrow...

2020-04-30 00:06 UTC, sbulen commented
*** Note I also removed the OFFSET for posts & PMs...  ***

The offset should be a #, a count of msgs, _usually a multiple of your LIMIT_.  BUT...  we were putting msg ids and pm ids in the offset.  Note that the logic saved off the last msg or pm retrieved, and subsequent calls included that in the WHERE clause.  So LIMIT by itself is appropriate here.  

In hindsight, I'm not sure how it worked before, with _both_ an OFFSET and a "where > last id_msg"...  

Input welcome.

2020-05-01 03:24 UTC, Sesquipedalian requested changes
I'm fine with removing the use of `OFFSET` from these queries, sure. I added that back in my first version of the export feature, but then I switched over to using `WHERE pm.id_pm > {int:start_after}` for greater efficiency, which means we no longer using the offset value at all.

However, if you remove `OFFSET` from these queries, you also need to remove all occurrences of `$context['xmlnews_offset']` in all files.

2020-05-01 20:47 UTC, sbulen commented
Done, & tests OK.  

I thought that was used by the xml feeds prior to #5081 ...  Interesting, it was defined, just never used.

2020-05-04 20:33 UTC, sbulen commented
@Sesquipedalian - if this looks good let me know, we can merge

2020-05-05 05:56 UTC, Sesquipedalian approved these changes

2020-05-05 05:56 UTC, merged