Pass $start to the memberlist columns
SimpleMachines/SMF pull request #6166
Opened 2020-06-25 07:18 UTC by live627

Issue found while looking into #6172

2020-06-30 22:25 UTC, jdarwood007 commented
Is $_REQUEST['start'] sanitized?

2020-07-05 22:49 UTC, Sesquipedalian requested changes

2020-07-05 22:49 UTC, Sesquipedalian commented on Sources/Memberlist.php
> +			$context['columns'][$col]['href'] = $scripturl . '?action=mlist;sa=search;start=' . $_REQUEST['start'] . ';sort=' . $col;
It looks like `$_REQUEST['start']` has not yet been sanitized at this point in `MLSearch()`. It should probably be cast to an integer before being used here.

2020-07-09 18:50 UTC, Sesquipedalian approved these changes

2020-07-09 18:50 UTC, merged