Registration password length error message fix. Fixes #6215
SimpleMachines/SMF pull request #6216
Opened 2020-08-04 13:29 UTC by Butterflysaway

Fixes #6215

2020-08-05 20:37 UTC, live627 requested changes
Can you please add a sign-off to all of your future commits?

2020-08-05 20:37 UTC, live627 commented on Sources/Subs-Members.php
> +			if($passwordError == 'short')
Can you please add a space after the if, Allman style?

2020-08-06 00:35 UTC, Butterflysaway commented
@live627 done.

2020-08-07 05:11 UTC, live627 approved these changes

2020-08-07 05:11 UTC, merged