Add title and buttons to admin and mod log
SimpleMachines/SMF pull request #6260
Opened 2020-09-11 06:22 UTC by albertlast

Base is for me the error log:
![grafik](https://user-images.githubusercontent.com/1782906/92873702-9cc00600-f407-11ea-8c22-5b67756b506b.png)

Atm the mod log look like this:
![grafik](https://user-images.githubusercontent.com/1782906/92873808-b5c8b700-f407-11ea-93d1-19747be847a9.png)
we notice missing title and missing button on right upper side
with the pr it's look like this:
![grafik](https://user-images.githubusercontent.com/1782906/92873933-d1cc5880-f407-11ea-8583-41049499566a.png)

2020-09-12 00:20 UTC, StealthWombat commented
Non-critical, but a good idea.

2020-10-03 11:23 UTC, dragomano commented
It should to add `loadLanguage('Admin+Modlog');` into Line 46 to prevent possible errors.

2020-10-03 21:40 UTC, albertlast commented
under which circumstance the line is needed?

2020-10-04 04:37 UTC, dragomano commented
1. Go to Moderate -> Moderation log
2. Then we see a new undefined error in the Error log:
`Undefined index: moderation_log`
3. Replace `loadLanguage('Modlog');` with `loadLanguage('Admin+Modlog');` and we do not see this error anymore.

2020-12-04 15:43 UTC, MissAllSunday commented
@albertlast Can you add the change @dragomano suggested?

2020-12-06 14:11 UTC, MissAllSunday requested changes

2020-12-06 14:11 UTC, MissAllSunday commented on Sources/Modlog.php
> +		'title' => $context['log_type'] === 3 ? $txt['admin_log'] : $txt['moderation_log'],
Since we historically haven't perform strict checks and due to the volatile nature of global vars, please use == insead of ===

2020-12-06 15:11 UTC, MissAllSunday approved these changes

2020-12-06 15:11 UTC, MissAllSunday commented
Thanks!

2020-12-06 15:11 UTC, merged