Load missing lang vars for SCEditor
SimpleMachines/SMF pull request #6362
Opened 2020-11-21 01:23 UTC by dragomano

We do not have translations for some elements of SCEditor's toolbar.

in Russian:
![2020-11-21 06_13_40-Id nihil adipisci ipsum  — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/99863796-9d240c80-2bc1-11eb-875b-240147d6544c.png)
in Spanish:
![2020-11-21 06_13_16-Id nihil adipisci ipsum  — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/99863793-9c8b7600-2bc1-11eb-9cef-ed046ee2ef48.png)

After this fix
in Russian::
![2020-11-21 06_14_02-Id nihil adipisci ipsum  — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/99863797-9d240c80-2bc1-11eb-8a90-d3346d7da546.png)
in Spanish:
![2020-11-21 06_14_17-Id nihil adipisci ipsum  — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/99863792-9bf2df80-2bc1-11eb-82e2-43ae3f6d4969.png)

Signed-off-by: Bugo <bugo@dragomano.ru>

2020-11-21 05:20 UTC, live627 commented
Thanks for all your work so far. 😃 

While testing this I noticed the email and URL popups are still English, as well as the more smileys option and the close button within said popup.

2020-11-24 04:19 UTC, live627 requested changes

2020-11-24 04:19 UTC, live627 commented on Sources/Subs-Editor.php
> +			"Description (optional):": "' . $editortxt['description'] . '",
Needs to be defined in the language file (Editor.english.php)

2020-11-24 04:19 UTC, live627 commented on Sources/Subs-Editor.php
> +			dateFormat: "' . $editortxt['dateformat'] . '"
Needs to be defined in the language file (Editor.english.php)

2020-11-24 07:08 UTC, dragomano commented on Sources/Subs-Editor.php
> +			dateFormat: "' . $editortxt['dateformat'] . '"
What exactly?

2020-11-24 07:51 UTC, live627 commented
$editortxt['dateformat']

$editortxt['description']

Maybe they could be in the error log?


On Tue, Nov 24, 2020 at 12:17 AM Bugo <notifications@github.com> wrote:

> *@dragomano* commented on this pull request.
> ------------------------------
>
> In Sources/Subs-Editor.php
> <https://github.com/SimpleMachines/SMF2.1/pull/6362#discussion_r529244970>
> :
>
> > @@ -1563,6 +1523,25 @@ function create_control_richedit($editorOptions)
>  		loadJavaScriptFile('editor.js', array('minimize' => true), 'smf_editor');
>  		loadJavaScriptFile('jquery.sceditor.bbcode.min.js', array(), 'smf_sceditor_bbcode');
>  		loadJavaScriptFile('jquery.sceditor.smf.js', array('minimize' => true), 'smf_sceditor_smf');
> +
> +		$scExtraLangs = '
> +		$.sceditor.locale["' . $txt['lang_dictionary'] . '"] = {
> +			"Width (optional):": "' . $editortxt['width'] . '",
> +			"Height (optional):": "' . $editortxt['height'] . '",
> +			"Insert": "' . $editortxt['insert'] . '",
> +			"Description (optional):": "' . $editortxt['description'] . '",
> +			"Rows:": "' . $editortxt['rows'] . '",
> +			"Cols:": "' . $editortxt['cols'] . '",
> +			"URL:": "' . $editortxt['url'] . '",
> +			"E-mail:": "' . $editortxt['email'] . '",
> +			"Video URL:": "' . $editortxt['video_url'] . '",
> +			"More": "' . $editortxt['more'] . '",
> +			"Close": "' . $editortxt['close'] . '",
> +			dateFormat: "' . $editortxt['dateformat'] . '"
>
> What exactly?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimpleMachines/SMF2.1/pull/6362#discussion_r529244970>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADJNN6TUBFIMBL2FWYQYXTSRNL37ANCNFSM4T5OJ2HQ>
> .
>

2020-11-24 08:19 UTC, dragomano commented
> $editortxt['dateformat'] $editortxt['description'] Maybe they could be in the error log?
But they [already are added](https://github.com/SimpleMachines/SMF2.1/pull/6362/commits/2034ad57e6ad7cc0a68dfa17d6f8c5ea46798f4c) in Editor.english.php, aren't they?
![](https://user-images.githubusercontent.com/229402/100067020-8eef1e00-2e57-11eb-9533-cb7f6a6cdf7c.png)

2020-11-24 08:53 UTC, live627 approved these changes
Yo, I didn't notice that and therefore didn't update that on my end. Sorry.

2020-11-24 08:53 UTC, merged