Check board_manager_groups when displaying permissions
SimpleMachines/SMF pull request #6452
Opened 2021-01-12 17:29 UTC by sbulen

Now that board managers can see all boards, this needs to be reflected on the 'Show Permissions' view.  

Otherwise, folks with 'Manage Boards and Categories' end up with boards on their restricted boards list, which doesn't make sense.

**_Before change:_**
![board_perms_conflict](https://user-images.githubusercontent.com/23568484/104349724-22d48200-54b8-11eb-80f2-28ca613e6e6b.png)

**_After change:_**
![board_perms_conflict-after](https://user-images.githubusercontent.com/23568484/104349740-27009f80-54b8-11eb-9f1d-4c8bbca2b3a0.png)

Saw then when researching #6450 .

2021-01-12 19:26 UTC, albertlast commented on Sources/Profile-View.php
> +		if ((count(array_intersect($curGroups, explode(',', $row['member_groups']))) === 0) && !$row['is_mod'] && (!empty($modSettings['board_manager_groups']) && count(array_intersect($curGroups, explode(
to many logic in one line for my pov.

2021-01-22 00:49 UTC, Sesquipedalian requested changes
Logic is good, but see suggestion for a more parsimonious way to accomplish it.

2021-01-22 00:49 UTC, Sesquipedalian commented on Sources/Profile-View.php
> +		if ((count(array_intersect($curGroups, explode(',', $row['member_groups']))) === 0) && !$row['is_mod'] && (!empty($modSettings['board_manager_groups']) && count(array_intersect($curGroups, explode(
```suggestion
		if (count(array_intersect($curGroups, array_merge(explode(',', $row['member_groups']), explode(',' $modSettings['board_manager_groups'])))) === 0)
```

2021-02-09 17:17 UTC, sbulen commented
Recent updates broke this PR...
![image](https://user-images.githubusercontent.com/23568484/107401232-8356df00-6ab7-11eb-9646-7b1a027d1f23.png)

I will simplify the language, retest & resubmit...

2021-02-09 21:43 UTC, sbulen commented
I split the logic to make it more readable.
Retested, & tests OK.
I did leave the existing logic, to be consistent with the checks in Load:
https://github.com/SimpleMachines/SMF2.1/blob/6a158f4d4c6d3fb00d165d0537837ef698303b3a/Sources/Load.php#L832

2021-02-10 12:31 UTC, live627 approved these changes

2021-02-10 12:33 UTC, merged