Add workaround if auto linker returns nothing
SimpleMachines/SMF pull request #6692
Opened 2021-04-14 08:43 UTC by BrickOzp

If a message contains an url that the auto linker can't parse
sometimes the whole message becomes empty. Add a workaround
to restore the message if that happens.

Workaround for #6685

Signed-off-by: Oscar Rydhé <oscar.rydhe@sony.com>

2021-04-18 01:03 UTC, jdarwood007 commented
I would rather see the proper fix than a workaround.

2021-04-19 05:45 UTC, BrickOzp commented
Generally I agree with you. I have tried to fix this particular url in https://github.com/SimpleMachines/SMF2.1/pull/6691. But if there are one that will break the regex, there can be more urls that breaks it that we do not know about. And I think it is better to display the post without auto linking than totally empty in those cases. That's why I also submitted this PR.

2021-05-15 01:21 UTC, Sesquipedalian requested changes
Using `is_null()` will be more precise than `empty()` in this case. 
Should also use the same logic in the email autolinker a few lines below, just in case that regex ever fails with an error.

2021-05-15 01:21 UTC, Sesquipedalian commented on Sources/Subs.php
>  						$data = preg_replace_callback('~' . $url_regex . '~i' . ($context['utf8'] ? 'u' : ''), function($matches)
```suggestion
						$tmp_data = preg_replace_callback('~' . $url_regex . '~i' . ($context['utf8'] ? 'u' : ''), function($matches)
```

2021-05-15 01:21 UTC, Sesquipedalian commented on Sources/Subs.php
> +						$data = $tmp_data;
```suggestion
					if (!is_null($tmp_data))
						$data = $tmp_data;
```

2021-05-20 19:41 UTC, Sesquipedalian requested changes

2021-05-20 19:41 UTC, Sesquipedalian commented on Sources/Subs.php
> +						$tmp_data = $data;
I don't think this line serves any purpose now.

2021-07-10 17:41 UTC, closed without merging