Load Security.php in maintenance mode 2
SimpleMachines/SMF pull request #6808
Opened 2021-06-28 05:53 UTC by BrickOzp

If the forum was in maintenance mode 2,
an undefined function error was displayed,
since Security.php was not loaded. Solve it
by loading it.

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

2021-06-28 05:54 UTC, BrickOzp commented
Reported here https://www.simplemachines.org/community/index.php?topic=578042.msg0

2021-06-28 21:03 UTC, Sesquipedalian submitted a review, later dismissed

2021-07-01 00:22 UTC, sbulen commented
Note this comment in the forum suggests a tweak may be needed:
https://www.simplemachines.org/community/index.php?topic=578068.0

2021-07-01 21:22 UTC, Sesquipedalian requested changes

2021-07-01 21:22 UTC, Sesquipedalian commented on index.php
> +require_once($sourcedir . '/Security.php');
Now that this is here, please remove the duplicate line of code that exists further down in the file.

2021-07-02 14:32 UTC, Sesquipedalian approved these changes

2021-07-06 21:06 UTC, merged