Use simple inserts
SimpleMachines/SMF pull request #6846
Opened 2021-07-15 02:57 UTC by sbulen

Fixes #6841 

Tested in both pg & mysql.  settings created properly & exports function properly.

2021-07-17 05:47 UTC, albertlast requested changes

2021-07-17 05:47 UTC, albertlast commented on other/upgrade_2-1_mysql.sql
---# missing

2021-07-17 05:47 UTC, albertlast commented on other/upgrade_2-1_postgresql.sql
---# missing

2021-07-17 17:44 UTC, sbulen commented
Changes made.  Good catch, thanks.

It is interesting that the upgrader didn't seem to care...

2021-07-23 00:05 UTC, live627 approved these changes

2021-07-23 00:06 UTC, merged