Adds missing $params['defer'] and $params['attributes'] from loadJava…
SimpleMachines/SMF pull request #6895
Opened 2021-08-01 10:23 UTC by WhistlingDonkey

Adds missing $params['defer'] and $params['attributes'] from loadJavaScriptFile and load CSSFile functions. Removes redundant $boardurl from previously applied and removed fix.

Fixes: #6894

Signed by WhistlingDonkey, github@pyro.life

2021-08-01 18:06 UTC, Sesquipedalian requested changes

2021-08-01 18:06 UTC, Sesquipedalian commented on Sources/Load.php
> +	$params['attributes'] = isset($params['attributes']) ? $params['attributes'] : false;
This should default to `array()` rather than `false`.

2021-08-01 18:06 UTC, Sesquipedalian commented on Sources/Load.php
> +	$params['attributes'] = isset($params['attributes']) ? $params['attributes'] : false;
This should default to `array()` rather than `false`.

2021-08-03 07:54 UTC, live627 approved these changes
Thank you for your contribution, @WhistlingDonkey!

2021-08-03 16:49 UTC, Sesquipedalian approved these changes

2021-08-03 16:51 UTC, merged