Lists smileys even when smiley_files table is empty
SimpleMachines/SMF pull request #6919
Opened 2021-08-07 22:05 UTC by Sesquipedalian

Fixes #6918

With this, smileys will still be listed in the various "Smileys and Message Icons" lists even if the smiley_files table is empty.

2021-08-08 21:50 UTC, sbulen requested changes
See note regarding dropdown

2021-08-09 00:28 UTC, Sesquipedalian commented
> See note regarding dropdown

Er, what note? Where?

2021-08-09 00:42 UTC, sbulen commented
If you see this note on some random unrelated issue, please ignore it over there....   🙄

The dropdown doesn't seem to work???
![image](https://user-images.githubusercontent.com/23568484/128650796-61954b4a-e902-4cfb-ae26-9efe527001f4.png)

2021-08-09 19:57 UTC, Sesquipedalian commented
Give it a try now, @sbulen. :)

2021-08-09 22:10 UTC, sbulen commented
Works now, thanks.

2021-08-09 22:10 UTC, sbulen approved these changes

2021-08-09 22:13 UTC, Sesquipedalian commented
Excellent

2021-08-09 22:13 UTC, merged