Improve the hooks list
SimpleMachines/SMF pull request #7106
Opened 2021-10-05 00:46 UTC by live627

- Greatly reduces the number of calls to `file_exists()` because it's kinda slow on Windows
- Fix sorting
- Functions with the same name but have different namespaces, classes, are now resolved correctly

The previous name resolution algorithm saws tightly wound in several loops (`num_files * nun_hooks *, num_functions`) and therefore could note scale at all. This is now changed so that all filesystem operations are outside of the main loops.

Filesystem operations on Windows can be a bit slow,    (NTFS) even with a SSD. So build a list of files from `$sourcedir` and use that to check for file existence before resorting to reading the disk.

Signed-off-by: John Rayes <live627@gmail.com>

2021-10-05 06:34 UTC, frandominguez03 commented
Thanks for the explanation! Quite interesting.

2021-10-05 18:04 UTC, Sesquipedalian commented
When no hooks have been added to the system, viewing the integration hooks admin page generates errors at the top of the page:
```
Notice
: Undefined index: function in
/Users/jon/Sites/dev/Sources/Subs-List.php
on line
90


Warning
: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in
/Users/jon/Sites/dev/Sources/Subs-List.php
on line
91
```

2021-10-05 19:07 UTC, Sesquipedalian requested changes
This is not yet a complete review, but here are a couple of things I noticed.

2021-10-05 19:07 UTC, Sesquipedalian commented on Sources/ManageMaintenance.php
> +					return $fileInfo->getExtension() == 'php';
The existing version of this function returns all files, not just PHP files. I do like the idea of filtering the list on the fly like this, but it would be better not to use a hard-coded extension. I suggest adding a second parameter to the function that takes an array of file extensions to filter by.

2021-10-05 19:07 UTC, Sesquipedalian commented on Sources/ManageMaintenance.php
> +	preg_match_all('/^namespace\s([a-z\\\]++)\s*;|class\s+(\w++)[\w\s]*{|function\s+(\w++)\s*\(.*\)[:\|\w\s]*{/im', $source, $matches, PREG_SET_ORDER);
```suggestion
	preg_match_all('/\bnamespace\s++((?P>label)(?:\\\(?P>label))*+)\s*+;|\bclass\s++((?P>label))[\w\s]*+{|\bfunction\s++((?P>label))\s*+\(.*\)[:\|\w\s]*+{(?(DEFINE)(?<label>[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*+))/i', $source, $matches, PREG_SET_ORDER);
```
1. Uses a `(?P>label)` subroutine, which is defined as `(?<label>[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]++)` inside the the `(?(DEFINE)...)` block, to more precisely match valid identifier labels for functions/classes/namespaces. The `[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*` definition comes from the PHP documentation [here](https://www.php.net/manual/en/language.variables.basics.php).
2. Uses `\b` before `namespace`, `class`, and `function` to better protect against, e.g. `looks_like_a_function_but_is_not`. This also allows removing the `^` and the need for multiline mode.

2021-10-06 23:04 UTC, live627 commented on Sources/ManageMaintenance.php
> +					return $fileInfo->getExtension() == 'php';
And this function was consumed by `get_integration_hooks_data()` which checked for that file  extension anyway.

2021-10-21 18:29 UTC, Sesquipedalian approved these changes

2021-10-21 18:30 UTC, Sesquipedalian commented on Sources/ManageMaintenance.php
> +					return $fileInfo->getExtension() == 'php';
Fair enough.

2021-10-21 18:43 UTC, merged