Fix comment in emails about reported messages
SimpleMachines/SMF pull request #7151
Opened 2021-11-10 07:55 UTC by BrickOzp

The comment in the email was not the comment left
by the reporter, but the actual message.

Fixes #7149

Signed-off-by: Oscar Rydhé <oscar.rydhe@gmail.com>

2021-11-10 07:57 UTC, BrickOzp commented
The report comments are stored in the log_reported_comments table.
I solved this by including the comment in the background task data.
If the data field is to small for this we could also solve this by including the comment id in the data
and query the log_reported_comments table in the task.

2021-11-10 17:52 UTC, Sesquipedalian commented
> If the data field is to small for this

Not a problem, I think. The `task_data` field is a MEDIUMTEXT, so there is plenty of room.

2021-11-10 17:56 UTC, Sesquipedalian requested changes

2021-11-10 17:56 UTC, Sesquipedalian commented on Sources/tasks/MsgReport-Notify.php
> -					'COMMENT' => $comment,
Since this is the only place that `$comment` is used, we may as well remove 'lr.body` and `$comment` from the query above.

2021-11-10 18:08 UTC, Sesquipedalian commented
Actually, on further consideration, I think it might be better to change the preceding query to something like this:
```
$request = $smcFunc['db_query']('', '
	SELECT lr.subject, lr.membername, lrc.comment
	FROM {db_prefix}log_reported AS lr
		INNER JOIN {db_prefix}log_reported AS lrc ON (lr.id_report = lrc.id_report)
	WHERE lr.id_report = {int:report}',
	array(
		'report' => $this->_details['report_id'],
	)
);
list ($subject, $poster_name, $comment) = $smcFunc['db_fetch_row']($request);
$smcFunc['db_free_result']($request);
```

2021-11-11 06:51 UTC, BrickOzp commented
If we pass the id_comment in the task we could do that query

2021-11-11 07:12 UTC, Sesquipedalian commented
That sounds like the perfect plan.

2021-11-15 20:34 UTC, Sesquipedalian approved these changes

2021-11-15 20:34 UTC, merged