Users without valid birthdates were falsely selected
SimpleMachines/SMF pull request #7201
Opened 2021-12-28 07:15 UTC by live627

- https://www.simplemachines.org/community/index.php?msg=4103960
-  #7140

2021-12-28 13:50 UTC, albertlast requested changes
one general question
and please use the date placeholder.

2021-12-28 13:50 UTC, albertlast commented on Sources/Subs-Calendar.php
> +				AND is_activated = 1',
i was believing that smf coding style is,
that static value also should be placed by placeholder?

2021-12-28 13:50 UTC, albertlast commented on Sources/Subs-Calendar.php
> +			WHERE birthdate != \'1004-01-01\'
please use date placeholder here ``{date:``

2021-12-28 13:50 UTC, albertlast commented on Sources/Subs-Calendar.php
> +			WHERE birthdate != \'1004-01-01\'
please use date placeholder here ``{date:``

2021-12-29 19:54 UTC, jdarwood007 commented
@live627 I agree with @albertlast here.  Can we use the proper place holders for the query?

The is_activated seems redundant now, but in future SMF versions, I would hope we can switch to using constants, so its cleaner code.

2021-12-30 15:09 UTC, jdarwood007 approved these changes

2021-12-30 15:16 UTC, albertlast approved these changes

2021-12-31 03:36 UTC, merged