pass the correct type to html_entity_decode()
SimpleMachines/SMF pull request #7231
Opened 2022-01-10 04:12 UTC by live627

Found while searching for a PM

- #7209

2022-01-12 03:21 UTC, Sesquipedalian requested changes
Actually, for all these cases the `null` was intended to tell PHP to use the default value. So instead of `0` these should all be changed to that default, i.e. `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401`.

2022-01-29 04:28 UTC, Oldiesmann commented
Note that the default flags changed in 8.1 according to the PHP manual. Prior to 8.1 it was ENT_COMPAT. I'm not sure how this affects us but we need to make sure we don't screw anything up with whichever flag(s) we choose

2022-01-29 08:14 UTC, Sesquipedalian commented
> Note that the default flags changed in 8.1 according to the PHP manual. Prior to 8.1 it was ENT_COMPAT. I'm not sure how this affects us but we need to make sure we don't screw anything up with whichever flag(s) we choose

True. Good catch.

... And actually, as I look at this PR again, I now realize that it doesn't make any difference which flags we use in these particular cases. None of the decoded entities here will be affected by any of those flags, so `0` is perfectly fine.

2022-01-29 08:14 UTC, Sesquipedalian approved these changes

2022-01-29 08:26 UTC, merged