Avoid errors unpacking ZIP file on PHP 7.0
SimpleMachines/SMF pull request #7319
Opened 2022-02-13 23:57 UTC by Sesquipedalian

(Maybe) fixes #7313

2022-02-14 02:45 UTC, live627 requested changes
ad dbyte lengths to substrrings

2022-02-14 02:45 UTC, live627 commented on Sources/Subs-Package.php
> +	$cdir = unpack('vdisk/@4/vdisk_entries/ventries/@12/Voffset', substr($data, $data_ecr + 4));
```suggestion
	$cdir = unpack('vdisk/@4/vdisk_entries/ventries/@12/Voffset', substr($data, $data_ecr + 4, 16));
```

2022-02-14 02:45 UTC, live627 commented on Sources/Subs-Package.php
> +		$header = unpack('Vcompressed_size/@8/vlen1/vlen2/vlen3/vdisk/@22/Voffset', substr($data, $pos_entry + 20));
```suggestion
		$header = unpack('Vcompressed_size/@8/vlen1/vlen2/vlen3/vdisk/@22/Voffset', substr($data, $pos_entry + 20, 26));
```

2022-02-14 02:45 UTC, live627 commented on Sources/Subs-Package.php
> +			substr($data, $header['offset'] + 6)
```suggestion
			substr($data, $header['offset'] + 6, 24)
```

2022-02-14 02:45 UTC, live627 commented on Sources/Subs-Package.php
> +			if (($general_purpose = unpack('Vcrc/Vcompressed_size/Vsize', substr($data, $gplen))) !== false)
```suggestion
			if (($general_purpose = unpack('Vcrc/Vcompressed_size/Vsize', substr($data, $gplen, 12))) !== false)
```

2022-02-14 08:57 UTC, BrickOzp commented
Works for me, php 7.0

2022-02-14 20:19 UTC, Sesquipedalian commented
@live627: Done.

@BrickOzp: Does everything still work for you on PHP 7.0 with the changes in 98ed90c?

2022-02-15 02:51 UTC, live627 approved these changes

2022-02-15 06:45 UTC, BrickOzp commented
Yes, it still works

2022-02-15 07:23 UTC, merged