Uses built-in 'matcher' callback of At.js
SimpleMachines/SMF pull request #7688
Opened 2023-02-24 01:25 UTC by Sesquipedalian

Fixes #7687

2023-02-24 02:04 UTC, jdarwood007 commented
#1794 was the PR that added that code.  Any issues you foresee from what that PR was trying to fix?

2023-02-24 05:46 UTC, Sesquipedalian commented
No. There was no description in that PR and I could not find a related issue, so I had to try to figure out what the purpose of the code changes was myself. As far as I can tell, the other changes in that PR did improve some stuff, whereas the custom 'matches' callback doesn't appear to have accomplished anything except introducing this bug. Perhaps the custom originally provided a workaround for a bug in At.js that was later solved upstream, but either way it doesn't do anything useful now.

For what its worth, I initially tried seeing if I could fix the custom code, and was making progress until I realized that my fixes were essentially just reimplementing what was in the default code anyway.

2023-02-24 22:16 UTC, live627 requested changes
I have found that the custom matcher required whitespace before the keyword to mat ch. This restores that behavior.

2023-02-24 22:16 UTC, live627 commented on Themes/default/scripts/mentions.js
>  	show_the_at: true,
```suggestion
	show_the_at: true,
	startWithSpace: true,
```

2023-02-24 22:38 UTC, Sesquipedalian commented
Nice. Suggestion committed.

2023-02-24 23:55 UTC, live627 approved these changes

2023-02-24 23:56 UTC, merged

2023-02-25 01:03 UTC, jdarwood007 commented
Thanks for the answer, I wasn't sure what the original code was intending to do either, so I was seeing if somebody else understood.

2023-02-25 01:36 UTC, live627 commented
I only figured it out because of the change in behavior after I applied the patch.