Fix integrate_attachments_browse hook to properly used
SimpleMachines/SMF pull request #7710
Opened 2023-03-17 19:50 UTC by dragomano

These changes will allow new heading sections to be added to and switched between the current sections.

![2023-03-18 00_45_59-Attachments and Avatars — Firefox Developer Edition](https://user-images.githubusercontent.com/229402/226014616-151e2c0c-86d8-44c3-bd82-a151335cdacf.png)

2023-03-18 04:44 UTC, live627 requested changes

2023-03-18 04:44 UTC, live627 commented on Sources/ManageAttachments.php
> + * @version 2.1.4
```suggestion
 * @version 2.1.3
```

2023-03-18 04:44 UTC, live627 commented on Sources/ManageAttachments.php
> + * @copyright 2023 Simple Machines and individual contributors
```suggestion
 * @copyright 2022 Simple Machines and individual contributors
```

2023-04-01 21:06 UTC, live627 commented
@jdarwood007 this will affect SimpleDesk

2023-04-01 22:08 UTC, jdarwood007 commented
I figured that.  I wrote the original hook function.  Its tagged for a future release though.

2023-06-14 23:48 UTC, live627 approved these changes

2023-06-15 04:01 UTC, merged