Handle basedir restrictions in php8
SimpleMachines/SMF pull request #7741
Opened 2023-05-03 06:32 UTC by sbulen

Fixes #7738 

In php 8+, open_basedir generates warnings & errors when you perform file read or write operations outside the constraints defined in open_basedir, in php or apache.  Some hosts use open_basedir to make sure you're not reading & writing where you shouldn't...

This PR addresses open_basedir issues associated with installing & unstalling mods, and using the package manager file permissions functions.

2023-05-04 11:14 UTC, isaak654 approved these changes
It definitely works for me.

2023-05-05 05:01 UTC, sbulen commented
Thanks for checking!

2023-05-05 11:57 UTC, isaak654 commented
I think it could still be improved. When you set the file permission function `Use predefined permission profile: Standard`, it will produce multiple open_basedir warnings
```
 Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7222
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7213
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7209
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2787
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2775
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2760
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Packages.php
Line: 2648
» Error Type 	general
```

2023-05-05 11:58 UTC, isaak654 requested changes
I think it could still be improved. When you set the file permission function `Use predefined permission profile: Standard`, it will produce multiple open_basedir warnings
```
 Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7222
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7213
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_writable(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs.php
Line: 7209
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2787
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2775
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: file_exists(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Subs-Package.php
Line: 2760
» Error Type 	general
» Time of Error 	Today at 01:53 PM
» Member ID that caused error 	1
» URL that caused error 	https://AVforum2.altervista.org/index.php?action=admin;area=packages;sa=perms;e664666a=e29b63c81067f8ab59e118a8605c33f0
» Error Message 	2: is_dir(): open_basedir restriction in effect. File(/membri/AVforum2/..) is not within the allowed path(s): (/membri/AVforum2/:/membri2/AVforum2/:/membri/.dummy/)
File: /membri/AVforum2/Sources/Packages.php
Line: 2648
» Error Type 	general
```

2023-07-15 08:03 UTC, live627 approved these changes
Tested and issues confirmed fixed.

2023-07-15 08:03 UTC, merged