The "(no primary membergroup)" option was missing when editing profiles
SimpleMachines/SMF pull request #7948
Opened 2023-12-10 01:40 UTC by Oldiesmann

The "(no primary membergroup)" option was missing from the profile, preventing you from being able to remove a member's primary group. I discovered this while trying to demote a test account from administrator to a regular user.

2023-12-21 06:35 UTC, Sesquipedalian commented on Sources/Profile.php
> +				// Gravatar?
This looks like a mistake.

2023-12-21 06:46 UTC, Sesquipedalian requested changes
Moved comment seems to be a mistake. Otherwise, looks good.

2023-12-21 06:46 UTC, Sesquipedalian commented on Sources/Profile.php
>  		if (
```suggestion
		// Gravatar?
		if (
```

2023-12-21 06:46 UTC, Sesquipedalian commented on Sources/Profile.php
> +				// Gravatar?
```suggestion
```

2023-12-21 06:47 UTC, Sesquipedalian commented on Sources/Profile.php
> +				// Gravatar?
```suggestion
		// Gravatar?
		if (
			$this->formatted['avatar']['allow_gravatar']
			&& (
				stristr($this->avatar['url'], 'gravatar://')
				|| !empty(Config::$modSettings['gravatarOverride'])
```

2023-12-21 13:59 UTC, Oldiesmann commented
Not sure how that happened. I'll fix it when I get home tonight 🙂

2023-12-22 05:02 UTC, jdarwood007 commented
PHP check is failing because of lint failure.  Nothing introduced by this PR far as I can tell.

2023-12-22 18:02 UTC, merged