[3.0] Replace AT.js (@mentions) with Tribute.js
SimpleMachines/SMF pull request #8132
Opened 2024-03-10 03:06 UTC by dragomano

The script used to mention users was updated 9 years ago, it would be nice to replace it.

The AT.js developer himself suggests using Tribute.js as a replacement, so I chose [one of the latest forks](https://github.com/SrPatinhas/tribute).

Features
* single script (`tribute.js`) instead of 2 (`jquery.atwho.min.js`, `jquery.caret.min.js`)
* no dependencies on jQuery
* there is no need to change the PHP backend code (we only change `mentions.js`)
* there is a possibility of fine tuning (see [options](https://github.com/SrPatinhas/tribute)

![sshot-2](https://github.com/SimpleMachines/SMF/assets/229402/26db3f8e-c960-4dc5-878d-2cb0db4d5032)

2024-03-10 03:19 UTC, live627 commented
Thanks! (just the emoji isn't enough)

2024-04-26 02:01 UTC, Sesquipedalian requested changes
I definitely like the idea of updating to a more recent and maintained script. 

However, more work needs to be done on this PR in order to make it fully compatible with SCEditor. In particular, the script only works when the editor is in source mode. It doesn't interact at all with the editor when it is in WYSIWYG mode.

Could you get this working with WYSIWYG mode, @dragomano? Once that is done, I will be glad to merge this PR.

2024-04-26 12:07 UTC, dragomano commented
If SCEditor is planned to be kept, it would be better to write a separate mentions plugin specifically for it. As it turns out, Tribute.js has issues with [support for iframe and WYSIWYG editors](https://github.com/zurb/tribute/issues?q=is%3Aissue+is%3Aopen+iframe).

2024-04-26 17:48 UTC, Sesquipedalian commented
> If SCEditor is planned to be kept

It is. If you want to find or create a solution that works with the WYSIWYG editor, that'd be lovely.

2024-04-27 03:20 UTC, dragomano commented
The modern solutions have the tendency to abandon BBCode. For example, CKEditor 4 has BBCode addon, and perfect [Mentions/ Tags and Emoji](https://ckeditor.com/docs/ckeditor4/latest/examples/mentions.html) addon (3 in 1), but CKEditor 4 reached its End of Life (EOL) in June 2023. And CKEditor 5 doesn't have BBCode addon.

2024-04-27 18:07 UTC, Sesquipedalian commented
Sorry if I wasn't clear. I meant that if you can find a solution to the problem that tribute.js doesn't work with SCEditor's WYSIWYG mode, that would be great. If that isn't possible, then we'll need to stick with at.js.

2025-08-08 18:53 UTC, jdarwood007 commented
@dragomano,  If you still plan this, a conflict exists.  But ensure that the issue you raised in #8820 doesn't return here.

2025-08-11 01:01 UTC, live627 commented
- #7933  completely rewrites at.js to be  native  ECMAScript.

2025-08-11 08:16 UTC, closed without merging