Report
SimpleMachines/SMF pull request #8186
Opened 2024-04-26 14:54 UTC by live627

- The Report controller uses the  new objects instead of raw SQL queries. Insert reference to Pinocchio saying "I'm a Real Boy now!"
- Add a new report type for board access. Well  actually it was moved from the board report in an attempt to be more accessible.
- Use JavaScript to split long tables, increasing readability and eliminating the need to scroll vertically . Who wants to do that?

I also have some code that adds checkboxes to filter the results by category mainly useful for board permissions. Shall I add a commit for that?

2024-04-29 19:01 UTC, Sesquipedalian submitted a review, later dismissed

2024-04-29 19:01 UTC, Sesquipedalian commented on Sources/Actions/Admin/Reports.php
> +				$disallowedGroups = explode(',', $board->deny_member_groups);
This line causes PHP to die with the following fatal error:
```
Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /path/to/forum/Sources/Actions/Admin/Reports.php:303 Stack trace: #0 /path/to/forum/Sources/Actions/Admin/Reports.php(303): explode(',', Array) #1 [internal function]: SMF\Actions\Admin\Reports->boards() #2 /path/to/forum/Sources/Actions/Admin/Reports.php(194): call_user_func(Array) #3 /path/to/forum/Sources/Actions/Admin/Reports.php(642): SMF\Actions\Admin\Reports->execute() #4 [internal function]: SMF\Actions\Admin\Reports::call() #5 /path/to/forum/Sources/Actions/Admin/ACP.php(786): call_user_func(Array) #6 /path/to/forum/Sources/Actions/Admin/ACP.php(813): SMF\Actions\Admin\ACP->execute() #7 [internal function]: SMF\Actions\Admin\ACP::call() #8 /path/to/forum/Sources/Forum.php(263): call_user_func(Array) #9 /path/to/forum/index.php(146): SMF\Forum->execute() #10 {main} thrown in /path/to/forum/Sources/Actions/Admin/Reports.php on line 303
```

2024-04-29 19:01 UTC, Sesquipedalian commented on Themes/default/scripts/reports.js
> +	//~ return;
Delete?

2024-04-29 19:01 UTC, Sesquipedalian commented
> I also have some code that adds checkboxes to filter the results by category mainly useful for board permissions. Shall I add a commit for that?

Sounds nice. Yes, please!

2024-04-30 11:08 UTC, live627 commented on Sources/Actions/Admin/Reports.php
> +				$disallowedGroups = explode(',', $board->deny_member_groups);
fixed

2024-04-30 11:10 UTC, live627 commented
added those extra checkboxes

2024-04-30 20:53 UTC, Sesquipedalian requested changes
1. The Board Access report uses the wrong title in the cat_bar's.
3. There is a useless duplicate table for each board in the Boards report. 
<img width="1198" alt="Screenshot 2024-04-30 at 2 49 17 PM" src="https://github.com/SimpleMachines/SMF/assets/191731/4321a544-f708-493e-a448-af34ef950fea"> Perhaps some more work needs to go into the logic that breaks up wide tables?
4. The checkboxes don't do anything. I suggested changing `<style>` to `<script>` below, which is necessary. However, even after I did that in my own tests, the JavaScript ran into syntax errors that will need to be fixed.

2024-04-30 20:53 UTC, Sesquipedalian commented on Themes/default/Reports.template.php
> +		<style>';
```suggestion
		<script>';
```

2024-04-30 20:53 UTC, Sesquipedalian commented on Themes/default/Reports.template.php
> +		</style>
```suggestion
		</script>
```

2024-05-01 06:02 UTC, live627 commented on Themes/default/Reports.template.php
> +		<style>';
thesee are actually css rules inspired by https://codepen.io/jlengstorf/pen/YzMwNrp

2024-05-01 21:25 UTC, Sesquipedalian approved these changes

2024-05-01 21:25 UTC, merged