Fix search issues
SimpleMachines/SMF pull request #8206
Opened 2024-05-09 05:25 UTC by Oldiesmann

This fixes two issues related to calculating the size of a search index.

1. PostgreSQL will throw an error if you try to get the size of something that doesn't exist. In order to properly handle actual database errors in the future, check to make sure the tables actually exist first (also because it's a simple operation).

2. For the custom index, we try to free the result regardless of whether we got one in the first place, which causes an error. This affects MySQL as well as Postgres.

On a related note, we need to properly handle database errors better - a query causing an error that leads to the request object being false instead of what we're looking for shouldn't cause a fatal PHP error.

2024-05-09 18:40 UTC, Sesquipedalian requested changes

2024-05-09 18:40 UTC, Sesquipedalian commented on Sources/Search/APIs/Custom.php
> -
You'll also need to add a `Db::$db->free_result($request);` inside the PostgreSQL section of the code higher up.

2024-05-09 18:40 UTC, Sesquipedalian commented on Sources/Search/APIs/Parsed.php
> +
```suggestion
			// Postgres will throw an error if the tables don't exist, so check first
			$search_tables = Db::$db->list_tables(Db::$db->name, Db::$db->prefix . 'log_search%');
			
			if (array_intersect([Db::$db->prefix . 'log_search_dictionary', Db::$db->prefix . 'log_search_parsed'], $search_tables) == []) {
				return $this->size;
			}

```

Keeps PHP-CS-Fixer happy.

2024-05-09 20:57 UTC, live627 commented
> On a related note, we need to properly handle database errors better - a query causing an error that leads to the request object being false instead of what we're looking for shouldn't cause a fatal PHP error.

I imagine that this can be fixed by copying the code from the mysql half

- https://github.com/SimpleMachines/SMF/pull/8146

2024-05-10 15:31 UTC, Sesquipedalian approved these changes

2024-05-10 15:31 UTC, merged