Fetch message for quotefast action via Msg object
SimpleMachines/SMF pull request #8335
Opened 2024-11-01 09:24 UTC by live627

### Motivation

I have a modification (Topic Descriptions) that needs access to this, so we'll use `Msg::load()` which eventually calls `integrate_query_message`

### Idea

`$query_customizations` could become its own object.

2024-11-02 02:06 UTC, jdarwood007 commented
Haven't run the code but looks good.

I'm in support of more objects for everything.  It makes things much easier to develop.  But we have to contend with how it would support customizations.  Magic methods maybe can help there.

2024-11-02 05:32 UTC, DiegoAndresCortes commented
I like it, same thing we got for messageindex, the more places the better imo

2024-11-02 14:36 UTC, tyrsson commented
From a customization perspective. If you model the instances that need to support customization as Observable then mods can be notified via their own registered listeners.

2024-11-28 01:29 UTC, Sesquipedalian requested changes

2024-11-28 01:29 UTC, Sesquipedalian commented on Sources/Actions/QuoteFast.php
> +			$query_customizations['where'][] = 't.locked = {int:not_locked}' . ($bq == '0=1' ? '' : 'm.' . $bq);
```suggestion
			$query_customizations['where'][] = 't.locked = {int:not_locked}' . ($bq == '0=1' ? '' : ' OR m.' . $bq);
```

Is this what you meant to write?

2024-11-28 14:47 UTC, Sesquipedalian approved these changes

2024-11-28 14:48 UTC, merged